using System.IO;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;

namespace Mosaic.Bridge.Tools.Simulation
{
    public static class SimAgentBasedTool
    {
        [MosaicTool("simulation/agent-based",
                    "Generates a Physarum slime mold agent-based simulation compute shader and manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<SimAgentBasedResult> Execute(SimAgentBasedParams p)
        {
            int   agentCount     = p.AgentCount     ?? 100000;
            float sensorAngle    = p.SensorAngle    ?? 30f;
            float sensorDistance = p.SensorDistance  ?? 9f;
            float turnSpeed      = p.TurnSpeed      ?? 2f;
            float moveSpeed      = p.MoveSpeed      ?? 1f;
            float trailWeight    = p.TrailWeight    ?? 5f;
            float decayRate      = p.DecayRate      ?? 0.95f;
            int   resolution     = p.Resolution     ?? 512;

            if (agentCount < 1 || agentCount > 4194304)
                return ToolResult<SimAgentBasedResult>.Fail(
                    "AgentCount must be between 1 and 4194304", ErrorCodes.INVALID_PARAM);
            if (resolution < 16 || resolution > 4096)
                return ToolResult<SimAgentBasedResult>.Fail(
                    "Resolution must be between 16 and 4096", ErrorCodes.INVALID_PARAM);
            if (decayRate < 0f || decayRate > 1f)
                return ToolResult<SimAgentBasedResult>.Fail(
                    "DecayRate must be between 0 and 1", ErrorCodes.INVALID_PARAM);

            string outputDir = p.OutputDirectory ?? "Assets/Generated/Simulation/AgentBased";
            if (!outputDir.StartsWith("Assets/"))
                return ToolResult<SimAgentBasedResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            string fullDir = Path.Combine(Application.dataPath, "..", outputDir);
            Directory.CreateDirectory(fullDir);

            // --- Compute Shader ---
            string computeAssetPath = $"{outputDir}/Physarum.compute";
            string computeFullPath  = Path.Combine(Application.dataPath, "..", computeAssetPath);
            string computeContent   = $@"// Generated by Mosaic Bridge - simulation/agent-based
// Customize as needed

#pragma kernel UpdateAgents
#pragma kernel DiffuseDecay

struct Agent
{{
    float2 position;
    float  angle;
}};

RWStructuredBuffer<Agent> _Agents;
RWTexture2D<float>        _TrailMap;
RWTexture2D<float>        _TrailMapOut;

uint   _AgentCount;
uint   _Resolution;
float  _SensorAngle;    // radians
float  _SensorDistance;  // {sensorDistance}
float  _TurnSpeed;      // {turnSpeed}
float  _MoveSpeed;      // {moveSpeed}
float  _TrailWeight;    // {trailWeight}
float  _DecayRate;      // {decayRate}
float  _DeltaTime;
float  _Time;

static const float PI = 3.14159265;

uint Hash(uint state)
{{
    state ^= 2747636419u;
    state *= 2654435769u;
    state ^= state >> 16;
    state *= 2654435769u;
    state ^= state >> 16;
    state *= 2654435769u;
    return state;
}}

float Sense(Agent agent, float sensorAngleOffset)
{{
    float sensorAngle = agent.angle + sensorAngleOffset;
    float2 sensorDir = float2(cos(sensorAngle), sin(sensorAngle));
    float2 sensorPos = agent.position + sensorDir * _SensorDistance;

    int2 sensorCoord = int2((int)sensorPos.x, (int)sensorPos.y);
    if (sensorCoord.x < 0 || sensorCoord.x >= (int)_Resolution ||
        sensorCoord.y < 0 || sensorCoord.y >= (int)_Resolution)
        return 0;

    return _TrailMap[uint2(sensorCoord)];
}}

[numthreads(256, 1, 1)]
void UpdateAgents(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _AgentCount) return;

    Agent agent = _Agents[id.x];

    // Random for stochastic turning
    uint random = Hash(agent.position.y * _Resolution + agent.position.x + Hash(id.x + (uint)(_Time * 100000)));

    // Sense left, center, right
    float sensorAngleRad = _SensorAngle * PI / 180.0;
    float weightForward = Sense(agent, 0);
    float weightLeft    = Sense(agent, sensorAngleRad);
    float weightRight   = Sense(agent, -sensorAngleRad);

    float randomSteer = (float)(random % 1000) / 1000.0;

    if (weightForward > weightLeft && weightForward > weightRight)
    {{
        // Continue forward
    }}
    else if (weightForward < weightLeft && weightForward < weightRight)
    {{
        // Random turn
        agent.angle += (randomSteer - 0.5) * 2.0 * _TurnSpeed * _DeltaTime;
    }}
    else if (weightRight > weightLeft)
    {{
        agent.angle -= _TurnSpeed * _DeltaTime;
    }}
    else if (weightLeft > weightRight)
    {{
        agent.angle += _TurnSpeed * _DeltaTime;
    }}

    // Move
    float2 dir = float2(cos(agent.angle), sin(agent.angle));
    float2 newPos = agent.position + dir * _MoveSpeed * _DeltaTime;

    // Wrap or bounce at boundaries
    if (newPos.x < 0 || newPos.x >= _Resolution || newPos.y < 0 || newPos.y >= _Resolution)
    {{
        newPos = clamp(newPos, 0, _Resolution - 1);
        agent.angle = (float)(random % 6283) / 1000.0; // random new angle
    }}

    agent.position = newPos;
    _Agents[id.x] = agent;

    // Deposit trail
    uint2 coord = uint2((uint)newPos.x, (uint)newPos.y);
    _TrailMap[coord] = min(_TrailMap[coord] + _TrailWeight * _DeltaTime, 1.0);
}}

[numthreads(8, 8, 1)]
void DiffuseDecay(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _Resolution || id.y >= _Resolution) return;

    // 3x3 box blur
    float sum = 0;
    for (int ox = -1; ox <= 1; ox++)
    {{
        for (int oy = -1; oy <= 1; oy++)
        {{
            int2 coord = int2((int)id.x + ox, (int)id.y + oy);
            coord = clamp(coord, 0, (int)_Resolution - 1);
            sum += _TrailMap[uint2(coord)];
        }}
    }}

    float blurred = sum / 9.0;
    _TrailMapOut[id.xy] = blurred * _DecayRate;
}}
";
            File.WriteAllText(computeFullPath, computeContent);
            AssetDatabase.ImportAsset(computeAssetPath);

            // --- Manager Script ---
            string managerAssetPath = $"{outputDir}/PhysarumManager.cs";
            string managerFullPath  = Path.Combine(Application.dataPath, "..", managerAssetPath);
            string managerContent   = $@"// Generated by Mosaic Bridge - simulation/agent-based
// Customize as needed

using UnityEngine;
using UnityEngine.UI;

public class PhysarumManager : MonoBehaviour
{{
    [Header(""Simulation Parameters"")]
    public int   agentCount     = {agentCount};
    public float sensorAngle    = {sensorAngle}f;
    public float sensorDistance  = {sensorDistance}f;
    public float turnSpeed      = {turnSpeed}f;
    public float moveSpeed      = {moveSpeed}f;
    public float trailWeight    = {trailWeight}f;
    public float decayRate      = {decayRate}f;
    public int   resolution     = {resolution};

    [Header(""References"")]
    public ComputeShader computeShader;
    public RawImage      displayImage;
    public Material      displayMaterial;

    private ComputeBuffer  _agentBuffer;
    private RenderTexture  _trailMapA;
    private RenderTexture  _trailMapB;
    private int _kUpdateAgents;
    private int _kDiffuseDecay;

    struct Agent
    {{
        public Vector2 position;
        public float   angle;
    }}

    void Start()
    {{
        _kUpdateAgents = computeShader.FindKernel(""UpdateAgents"");
        _kDiffuseDecay = computeShader.FindKernel(""DiffuseDecay"");

        // Create agent buffer
        _agentBuffer = new ComputeBuffer(agentCount, sizeof(float) * 3);
        var agents = new Agent[agentCount];
        for (int i = 0; i < agentCount; i++)
        {{
            float angle = Random.Range(0f, Mathf.PI * 2f);
            float radius = Random.Range(0f, resolution * 0.4f);
            agents[i].position = new Vector2(resolution / 2f, resolution / 2f) +
                new Vector2(Mathf.Cos(angle), Mathf.Sin(angle)) * radius;
            agents[i].angle = angle + Mathf.PI; // face center
        }}
        _agentBuffer.SetData(agents);

        // Create trail map render textures
        _trailMapA = new RenderTexture(resolution, resolution, 0, RenderTextureFormat.RFloat);
        _trailMapA.enableRandomWrite = true;
        _trailMapA.Create();

        _trailMapB = new RenderTexture(resolution, resolution, 0, RenderTextureFormat.RFloat);
        _trailMapB.enableRandomWrite = true;
        _trailMapB.Create();

        if (displayImage != null)
            displayImage.texture = _trailMapA;
    }}

    void Update()
    {{
        float dt = Time.deltaTime;

        computeShader.SetInt(""_AgentCount"", agentCount);
        computeShader.SetInt(""_Resolution"", resolution);
        computeShader.SetFloat(""_SensorAngle"", sensorAngle);
        computeShader.SetFloat(""_SensorDistance"", sensorDistance);
        computeShader.SetFloat(""_TurnSpeed"", turnSpeed);
        computeShader.SetFloat(""_MoveSpeed"", moveSpeed);
        computeShader.SetFloat(""_TrailWeight"", trailWeight);
        computeShader.SetFloat(""_DecayRate"", decayRate);
        computeShader.SetFloat(""_DeltaTime"", dt);
        computeShader.SetFloat(""_Time"", Time.time);

        // Update agents
        int agentGroups = Mathf.CeilToInt(agentCount / 256f);
        computeShader.SetBuffer(_kUpdateAgents, ""_Agents"", _agentBuffer);
        computeShader.SetTexture(_kUpdateAgents, ""_TrailMap"", _trailMapA);
        computeShader.Dispatch(_kUpdateAgents, agentGroups, 1, 1);

        // Diffuse and decay
        int texGroups = Mathf.CeilToInt(resolution / 8f);
        computeShader.SetTexture(_kDiffuseDecay, ""_TrailMap"",    _trailMapA);
        computeShader.SetTexture(_kDiffuseDecay, ""_TrailMapOut"", _trailMapB);
        computeShader.Dispatch(_kDiffuseDecay, texGroups, texGroups, 1);

        // Swap
        var tmp = _trailMapA;
        _trailMapA = _trailMapB;
        _trailMapB = tmp;

        if (displayImage != null)
            displayImage.texture = _trailMapA;
        if (displayMaterial != null)
            displayMaterial.mainTexture = _trailMapA;
    }}

    void OnDestroy()
    {{
        _agentBuffer?.Release();
        if (_trailMapA != null) Destroy(_trailMapA);
        if (_trailMapB != null) Destroy(_trailMapB);
    }}
}}
";
            File.WriteAllText(managerFullPath, managerContent);
            AssetDatabase.ImportAsset(managerAssetPath);

            return ToolResult<SimAgentBasedResult>.Ok(new SimAgentBasedResult
            {
                ComputeShaderPath = computeAssetPath,
                ManagerScriptPath = managerAssetPath,
                AgentCount        = agentCount,
                Resolution        = resolution
            });
        }
    }
}
