using System.IO;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Tools.Shared;

namespace Mosaic.Bridge.Tools.Simulation
{
    public static class SimBoidsTool
    {
        [MosaicTool("simulation/boids",
                    "Generates a Reynolds flocking (boids) simulation compute shader and manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<SimBoidsResult> Execute(SimBoidsParams p)
        {
            int   boidCount        = p.BoidCount        ?? 1024;
            float separationWeight = p.SeparationWeight  ?? 1.5f;
            float alignmentWeight  = p.AlignmentWeight   ?? 1.0f;
            float cohesionWeight   = p.CohesionWeight    ?? 1.0f;
            float maxSpeed         = p.MaxSpeed          ?? 5f;
            float viewRadius       = p.ViewRadius        ?? 2.5f;
            float avoidRadius      = p.AvoidRadius       ?? 1.0f;
            float boundarySize     = p.BoundarySize      ?? 20f;

            if (boidCount < 1 || boidCount > 1048576)
                return ToolResult<SimBoidsResult>.Fail(
                    "BoidCount must be between 1 and 1048576", ErrorCodes.INVALID_PARAM);

            string outputDir = p.OutputDirectory ?? "Assets/Generated/Simulation/Boids";
            if (!outputDir.StartsWith("Assets/"))
                return ToolResult<SimBoidsResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            AssetDatabaseHelper.EnsureFolder(outputDir);
            string fullDir = Path.Combine(Application.dataPath, "..", outputDir);

            // --- Compute Shader ---
            string computeAssetPath = $"{outputDir}/Boids.compute";
            string computeFullPath  = Path.Combine(Application.dataPath, "..", computeAssetPath);
            string computeContent   = $@"// Generated by Mosaic Bridge - simulation/boids
// Customize as needed

#pragma kernel UpdateBoids

struct Boid
{{
    float3 position;
    float3 velocity;
}};

RWStructuredBuffer<Boid> _Boids;

uint   _BoidCount;
float  _SeparationWeight; // {separationWeight}
float  _AlignmentWeight;  // {alignmentWeight}
float  _CohesionWeight;   // {cohesionWeight}
float  _MaxSpeed;         // {maxSpeed}
float  _ViewRadius;       // {viewRadius}
float  _AvoidRadius;      // {avoidRadius}
float  _BoundarySize;     // {boundarySize}
float  _DeltaTime;

[numthreads(256, 1, 1)]
void UpdateBoids(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _BoidCount) return;

    float3 pos = _Boids[id.x].position;
    float3 vel = _Boids[id.x].velocity;

    float3 separation = float3(0, 0, 0);
    float3 alignment  = float3(0, 0, 0);
    float3 cohesion   = float3(0, 0, 0);
    int    neighbors  = 0;

    for (uint j = 0; j < _BoidCount; j++)
    {{
        if (j == id.x) continue;
        float3 diff = pos - _Boids[j].position;
        float dist = length(diff);

        if (dist < _ViewRadius)
        {{
            // Separation
            if (dist < _AvoidRadius && dist > 0.001)
            {{
                separation += normalize(diff) / dist;
            }}

            // Alignment
            alignment += _Boids[j].velocity;

            // Cohesion
            cohesion += _Boids[j].position;

            neighbors++;
        }}
    }}

    if (neighbors > 0)
    {{
        alignment /= (float)neighbors;
        alignment = normalize(alignment) * _MaxSpeed - vel;

        cohesion /= (float)neighbors;
        cohesion = normalize(cohesion - pos) * _MaxSpeed - vel;
    }}

    float3 accel = separation * _SeparationWeight
                 + alignment  * _AlignmentWeight
                 + cohesion   * _CohesionWeight;

    // Boundary steering
    float half = _BoundarySize * 0.5;
    float turnFactor = 1.0;
    if (pos.x < -half) accel.x += turnFactor;
    if (pos.x >  half) accel.x -= turnFactor;
    if (pos.y < -half) accel.y += turnFactor;
    if (pos.y >  half) accel.y -= turnFactor;
    if (pos.z < -half) accel.z += turnFactor;
    if (pos.z >  half) accel.z -= turnFactor;

    vel += accel * _DeltaTime;
    float speed = length(vel);
    if (speed > _MaxSpeed)
        vel = normalize(vel) * _MaxSpeed;

    pos += vel * _DeltaTime;

    _Boids[id.x].position = pos;
    _Boids[id.x].velocity = vel;
}}
";
            File.WriteAllText(computeFullPath, computeContent);
            AssetDatabase.ImportAsset(computeAssetPath);

            // --- Manager Script ---
            string managerAssetPath = $"{outputDir}/BoidsManager.cs";
            string managerFullPath  = Path.Combine(Application.dataPath, "..", managerAssetPath);
            string managerContent   = $@"// Generated by Mosaic Bridge - simulation/boids
// Customize as needed

using UnityEngine;

public class BoidsManager : MonoBehaviour
{{
    [Header(""Simulation Parameters"")]
    public int   boidCount        = {boidCount};
    public float separationWeight = {separationWeight}f;
    public float alignmentWeight  = {alignmentWeight}f;
    public float cohesionWeight   = {cohesionWeight}f;
    public float maxSpeed         = {maxSpeed}f;
    public float viewRadius       = {viewRadius}f;
    public float avoidRadius      = {avoidRadius}f;
    public float boundarySize     = {boundarySize}f;

    [Header(""Rendering"")]
    public ComputeShader computeShader;
    public Mesh          boidMesh;
    public Material      boidMaterial;

    private ComputeBuffer _boidBuffer;
    private ComputeBuffer _argsBuffer;
    private int _kernelUpdate;
    private int _threadGroups;

    struct Boid
    {{
        public Vector3 position;
        public Vector3 velocity;
    }}

    void Start()
    {{
        _kernelUpdate = computeShader.FindKernel(""UpdateBoids"");

        int stride = sizeof(float) * 6; // 3+3
        _boidBuffer = new ComputeBuffer(boidCount, stride);

        var boids = new Boid[boidCount];
        for (int i = 0; i < boidCount; i++)
        {{
            boids[i].position = Random.insideUnitSphere * boundarySize * 0.4f;
            boids[i].velocity = Random.insideUnitSphere * maxSpeed * 0.5f;
        }}
        _boidBuffer.SetData(boids);

        _threadGroups = Mathf.CeilToInt(boidCount / 256f);

        _argsBuffer = new ComputeBuffer(1, 5 * sizeof(uint), ComputeBufferType.IndirectArguments);
        uint[] args = new uint[5];
        args[0] = boidMesh ? boidMesh.GetIndexCount(0) : 0;
        args[1] = (uint)boidCount;
        args[2] = boidMesh ? boidMesh.GetIndexStart(0) : 0;
        args[3] = boidMesh ? boidMesh.GetBaseVertex(0) : 0;
        args[4] = 0;
        _argsBuffer.SetData(args);
    }}

    void Update()
    {{
        computeShader.SetInt(""_BoidCount"", boidCount);
        computeShader.SetFloat(""_SeparationWeight"", separationWeight);
        computeShader.SetFloat(""_AlignmentWeight"", alignmentWeight);
        computeShader.SetFloat(""_CohesionWeight"", cohesionWeight);
        computeShader.SetFloat(""_MaxSpeed"", maxSpeed);
        computeShader.SetFloat(""_ViewRadius"", viewRadius);
        computeShader.SetFloat(""_AvoidRadius"", avoidRadius);
        computeShader.SetFloat(""_BoundarySize"", boundarySize);
        computeShader.SetFloat(""_DeltaTime"", Time.deltaTime);

        computeShader.SetBuffer(_kernelUpdate, ""_Boids"", _boidBuffer);
        computeShader.Dispatch(_kernelUpdate, _threadGroups, 1, 1);

        if (boidMesh != null && boidMaterial != null)
        {{
            boidMaterial.SetBuffer(""_Boids"", _boidBuffer);
            Graphics.DrawMeshInstancedIndirect(boidMesh, 0, boidMaterial,
                new Bounds(Vector3.zero, Vector3.one * boundarySize), _argsBuffer);
        }}
    }}

    void OnDestroy()
    {{
        _boidBuffer?.Release();
        _argsBuffer?.Release();
    }}
}}
";
            File.WriteAllText(managerFullPath, managerContent);
            AssetDatabase.ImportAsset(managerAssetPath);

            return ToolResult<SimBoidsResult>.Ok(new SimBoidsResult
            {
                ComputeShaderPath = computeAssetPath,
                ManagerScriptPath = managerAssetPath,
                BoidCount         = boidCount
            });
        }
    }
}
