using System.IO;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Tools.Shared;

namespace Mosaic.Bridge.Tools.Simulation
{
    public static class SimClothTool
    {
        [MosaicTool("simulation/cloth",
                    "Generates a spring-mass cloth simulation compute shader and manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<SimClothResult> Execute(SimClothParams p)
        {
            int   width       = p.Width                ?? 32;
            int   height      = p.Height               ?? 32;
            float spacing     = p.Spacing              ?? 0.25f;
            float gravity     = p.Gravity              ?? -9.81f;
            float stiffness   = p.Stiffness            ?? 800f;
            float damping     = p.Damping              ?? 5f;
            int   iterations  = p.ConstraintIterations ?? 5;

            int particleCount = width * height;

            if (width < 2 || height < 2)
                return ToolResult<SimClothResult>.Fail(
                    "Width and Height must be at least 2", ErrorCodes.INVALID_PARAM);
            if (particleCount > 262144)
                return ToolResult<SimClothResult>.Fail(
                    "Total particle count (Width*Height) must not exceed 262144", ErrorCodes.INVALID_PARAM);

            string outputDir = p.OutputDirectory ?? "Assets/Generated/Simulation/Cloth";
            if (!outputDir.StartsWith("Assets/"))
                return ToolResult<SimClothResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            AssetDatabaseHelper.EnsureFolder(outputDir);
            string fullDir = Path.Combine(Application.dataPath, "..", outputDir);

            // --- Compute Shader ---
            string computeAssetPath = $"{outputDir}/ClothSim.compute";
            string computeFullPath  = Path.Combine(Application.dataPath, "..", computeAssetPath);
            string computeContent   = $@"// Generated by Mosaic Bridge - simulation/cloth
// Customize as needed

#pragma kernel ApplyForces
#pragma kernel SolveConstraints
#pragma kernel UpdatePositions

struct ClothParticle
{{
    float3 position;
    float3 previousPosition;
    float3 acceleration;
    int    pinned;
}};

RWStructuredBuffer<ClothParticle> _Particles;

uint   _Width;
uint   _Height;
uint   _ParticleCount;
float  _Spacing;     // {spacing}
float  _Gravity;     // {gravity}
float  _Stiffness;   // {stiffness}
float  _Damping;     // {damping}
float  _DeltaTime;
float3 _Wind;

[numthreads(256, 1, 1)]
void ApplyForces(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _ParticleCount) return;
    if (_Particles[id.x].pinned == 1) return;

    float3 acc = float3(0, _Gravity, 0) + _Wind;
    _Particles[id.x].acceleration = acc;
}}

void SolveDistanceConstraint(uint idxA, uint idxB, float restLength)
{{
    float3 delta = _Particles[idxB].position - _Particles[idxA].position;
    float dist = length(delta);
    if (dist < 1e-6) return;

    float diff = (dist - restLength) / dist;
    float3 correction = delta * 0.5 * diff;

    if (_Particles[idxA].pinned == 0)
        _Particles[idxA].position += correction;
    if (_Particles[idxB].pinned == 0)
        _Particles[idxB].position -= correction;
}}

[numthreads(256, 1, 1)]
void SolveConstraints(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _ParticleCount) return;

    uint x = id.x % _Width;
    uint y = id.x / _Width;

    float structDist = _Spacing;
    float shearDist  = _Spacing * 1.41421356; // sqrt(2)
    float bendDist   = _Spacing * 2.0;

    // Structural (right)
    if (x + 1 < _Width)
        SolveDistanceConstraint(id.x, id.x + 1, structDist);

    // Structural (down)
    if (y + 1 < _Height)
        SolveDistanceConstraint(id.x, id.x + _Width, structDist);

    // Shear (down-right)
    if (x + 1 < _Width && y + 1 < _Height)
        SolveDistanceConstraint(id.x, id.x + _Width + 1, shearDist);

    // Shear (down-left)
    if (x > 0 && y + 1 < _Height)
        SolveDistanceConstraint(id.x, id.x + _Width - 1, shearDist);

    // Bend (right 2)
    if (x + 2 < _Width)
        SolveDistanceConstraint(id.x, id.x + 2, bendDist);

    // Bend (down 2)
    if (y + 2 < _Height)
        SolveDistanceConstraint(id.x, id.x + _Width * 2, bendDist);
}}

[numthreads(256, 1, 1)]
void UpdatePositions(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _ParticleCount) return;
    if (_Particles[id.x].pinned == 1) return;

    float3 pos  = _Particles[id.x].position;
    float3 prev = _Particles[id.x].previousPosition;
    float3 acc  = _Particles[id.x].acceleration;

    // Verlet integration with damping
    float3 newPos = pos + (pos - prev) * (1.0 - _Damping * _DeltaTime) + acc * _DeltaTime * _DeltaTime;

    _Particles[id.x].previousPosition = pos;
    _Particles[id.x].position = newPos;
}}
";
            File.WriteAllText(computeFullPath, computeContent);
            AssetDatabase.ImportAsset(computeAssetPath);

            // --- Manager Script ---
            string managerAssetPath = $"{outputDir}/ClothSimManager.cs";
            string managerFullPath  = Path.Combine(Application.dataPath, "..", managerAssetPath);
            string managerContent   = $@"// Generated by Mosaic Bridge - simulation/cloth
// Customize as needed

using UnityEngine;

[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]
public class ClothSimManager : MonoBehaviour
{{
    [Header(""Cloth Parameters"")]
    public int   width      = {width};
    public int   height     = {height};
    public float spacing    = {spacing}f;
    public float gravity    = {gravity}f;
    public float stiffness  = {stiffness}f;
    public float damping    = {damping}f;
    public int   constraintIterations = {iterations};

    [Header(""Wind"")]
    public Vector3 wind = new Vector3(0.5f, 0, 0.3f);

    [Header(""References"")]
    public ComputeShader computeShader;

    private ComputeBuffer _particleBuffer;
    private int _kApplyForces;
    private int _kSolveConstraints;
    private int _kUpdatePositions;
    private int _threadGroups;
    private int _particleCount;

    private Mesh _mesh;
    private Vector3[] _vertices;

    struct ClothParticle
    {{
        public Vector3 position;
        public Vector3 previousPosition;
        public Vector3 acceleration;
        public int     pinned;
    }}

    void Start()
    {{
        _particleCount = width * height;
        _kApplyForces       = computeShader.FindKernel(""ApplyForces"");
        _kSolveConstraints  = computeShader.FindKernel(""SolveConstraints"");
        _kUpdatePositions   = computeShader.FindKernel(""UpdatePositions"");

        int stride = sizeof(float) * 9 + sizeof(int); // 3+3+3 floats + 1 int
        _particleBuffer = new ComputeBuffer(_particleCount, stride);

        var particles = new ClothParticle[_particleCount];
        for (int y = 0; y < height; y++)
        {{
            for (int x = 0; x < width; x++)
            {{
                int idx = y * width + x;
                Vector3 pos = new Vector3(x * spacing, 0, y * spacing);
                particles[idx].position = pos;
                particles[idx].previousPosition = pos;
                particles[idx].acceleration = Vector3.zero;
                particles[idx].pinned = (y == height - 1) ? 1 : 0; // pin top row
            }}
        }}
        _particleBuffer.SetData(particles);

        _threadGroups = Mathf.CeilToInt(_particleCount / 256f);

        // Create mesh
        _mesh = new Mesh();
        _mesh.indexFormat = _particleCount > 65535
            ? UnityEngine.Rendering.IndexFormat.UInt32
            : UnityEngine.Rendering.IndexFormat.UInt16;

        _vertices = new Vector3[_particleCount];
        for (int i = 0; i < _particleCount; i++)
            _vertices[i] = particles[i].position;
        _mesh.vertices = _vertices;

        var uv = new Vector2[_particleCount];
        for (int y = 0; y < height; y++)
            for (int x = 0; x < width; x++)
                uv[y * width + x] = new Vector2((float)x / (width - 1), (float)y / (height - 1));
        _mesh.uv = uv;

        int[] tris = new int[(width - 1) * (height - 1) * 6];
        int t = 0;
        for (int y = 0; y < height - 1; y++)
        {{
            for (int x = 0; x < width - 1; x++)
            {{
                int i = y * width + x;
                tris[t++] = i;
                tris[t++] = i + width;
                tris[t++] = i + 1;
                tris[t++] = i + 1;
                tris[t++] = i + width;
                tris[t++] = i + width + 1;
            }}
        }}
        _mesh.triangles = tris;
        _mesh.RecalculateNormals();

        GetComponent<MeshFilter>().mesh = _mesh;
    }}

    void Update()
    {{
        float dt = Time.deltaTime;

        computeShader.SetInt(""_Width"", width);
        computeShader.SetInt(""_Height"", height);
        computeShader.SetInt(""_ParticleCount"", _particleCount);
        computeShader.SetFloat(""_Spacing"", spacing);
        computeShader.SetFloat(""_Gravity"", gravity);
        computeShader.SetFloat(""_Stiffness"", stiffness);
        computeShader.SetFloat(""_Damping"", damping);
        computeShader.SetFloat(""_DeltaTime"", dt);
        computeShader.SetVector(""_Wind"", wind);

        computeShader.SetBuffer(_kApplyForces,      ""_Particles"", _particleBuffer);
        computeShader.SetBuffer(_kSolveConstraints,  ""_Particles"", _particleBuffer);
        computeShader.SetBuffer(_kUpdatePositions,   ""_Particles"", _particleBuffer);

        computeShader.Dispatch(_kApplyForces, _threadGroups, 1, 1);

        for (int i = 0; i < constraintIterations; i++)
            computeShader.Dispatch(_kSolveConstraints, _threadGroups, 1, 1);

        computeShader.Dispatch(_kUpdatePositions, _threadGroups, 1, 1);

        // Read back for mesh update
        var data = new ClothParticle[_particleCount];
        _particleBuffer.GetData(data);
        for (int i = 0; i < _particleCount; i++)
            _vertices[i] = data[i].position;
        _mesh.vertices = _vertices;
        _mesh.RecalculateNormals();
    }}

    void OnDestroy()
    {{
        _particleBuffer?.Release();
    }}
}}
";
            File.WriteAllText(managerFullPath, managerContent);
            AssetDatabase.ImportAsset(managerAssetPath);

            return ToolResult<SimClothResult>.Ok(new SimClothResult
            {
                ComputeShaderPath = computeAssetPath,
                ManagerScriptPath = managerAssetPath,
                Width             = width,
                Height            = height,
                ParticleCount     = particleCount
            });
        }
    }
}
