using System.IO;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Tools.Shared;

namespace Mosaic.Bridge.Tools.Simulation
{
    public static class SimEcosystemTool
    {
        [MosaicTool("simulation/ecosystem",
                    "Generates a predator-prey ecosystem simulation compute shader and manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<SimEcosystemResult> Execute(SimEcosystemParams p)
        {
            int   preyCount            = p.PreyCount            ?? 500;
            int   predatorCount        = p.PredatorCount        ?? 50;
            float preyReproductionRate = p.PreyReproductionRate ?? 0.04f;
            float predatorDeathRate    = p.PredatorDeathRate    ?? 0.02f;
            float catchRadius          = p.CatchRadius          ?? 1.5f;
            float worldSize            = p.WorldSize            ?? 50f;
            int   maxPopulation        = p.MaxPopulation        ?? 5000;

            if (preyCount < 1 || predatorCount < 1)
                return ToolResult<SimEcosystemResult>.Fail(
                    "PreyCount and PredatorCount must be at least 1", ErrorCodes.INVALID_PARAM);
            if (preyCount + predatorCount > maxPopulation)
                return ToolResult<SimEcosystemResult>.Fail(
                    "Initial population exceeds MaxPopulation", ErrorCodes.INVALID_PARAM);

            string outputDir = p.OutputDirectory ?? "Assets/Generated/Simulation/Ecosystem";
            if (!outputDir.StartsWith("Assets/"))
                return ToolResult<SimEcosystemResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            AssetDatabaseHelper.EnsureFolder(outputDir);
            string fullDir = Path.Combine(Application.dataPath, "..", outputDir);

            // --- Compute Shader ---
            string computeAssetPath = $"{outputDir}/Ecosystem.compute";
            string computeFullPath  = Path.Combine(Application.dataPath, "..", computeAssetPath);
            string computeContent   = $@"// Generated by Mosaic Bridge - simulation/ecosystem
// Customize as needed

#pragma kernel UpdatePrey
#pragma kernel UpdatePredators

struct Agent
{{
    float3 position;
    float3 velocity;
    float  energy;
    int    alive;
    int    type; // 0 = prey, 1 = predator
}};

RWStructuredBuffer<Agent> _Agents;

uint   _MaxPopulation;
uint   _PreyCount;
uint   _PredatorCount;
float  _PreyReproductionRate;
float  _PredatorDeathRate;
float  _CatchRadius;
float  _WorldSize;
float  _DeltaTime;
float  _Time;

uint Hash(uint state)
{{
    state ^= 2747636419u;
    state *= 2654435769u;
    state ^= state >> 16;
    state *= 2654435769u;
    return state;
}}

float3 RandomDir(uint seed)
{{
    float a = (float)(seed % 6283) / 1000.0;
    return float3(cos(a), 0, sin(a));
}}

[numthreads(256, 1, 1)]
void UpdatePrey(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _MaxPopulation) return;

    Agent agent = _Agents[id.x];
    if (agent.alive == 0 || agent.type != 0) return;

    uint rng = Hash(id.x + (uint)(_Time * 1000));

    // Flee from nearest predator
    float3 fleeDir = float3(0, 0, 0);
    float closestPredDist = 1e10;
    for (uint j = 0; j < _MaxPopulation; j++)
    {{
        if (_Agents[j].alive == 0 || _Agents[j].type != 1) continue;
        float3 diff = agent.position - _Agents[j].position;
        float dist = length(diff);
        if (dist < closestPredDist && dist > 0.001)
        {{
            closestPredDist = dist;
            fleeDir = normalize(diff);
        }}
    }}

    // Wander + flee
    float3 wander = RandomDir(rng) * 0.5;
    float fleeFactor = closestPredDist < 10.0 ? 2.0 : 0.0;
    agent.velocity = normalize(wander + fleeDir * fleeFactor) * 3.0;
    agent.position += agent.velocity * _DeltaTime;

    // Boundary wrap
    float half = _WorldSize * 0.5;
    if (agent.position.x > half)  agent.position.x -= _WorldSize;
    if (agent.position.x < -half) agent.position.x += _WorldSize;
    if (agent.position.z > half)  agent.position.z -= _WorldSize;
    if (agent.position.z < -half) agent.position.z += _WorldSize;
    agent.position.y = 0;

    // Energy and reproduction
    agent.energy += _DeltaTime;
    if (agent.energy > 1.0 / _PreyReproductionRate)
    {{
        agent.energy = 0;
        // Try to find dead slot for offspring
        uint slot = Hash(rng + id.x) % _MaxPopulation;
        if (_Agents[slot].alive == 0)
        {{
            Agent baby;
            baby.position = agent.position + RandomDir(Hash(slot)) * 0.5;
            baby.velocity = float3(0, 0, 0);
            baby.energy = 0;
            baby.alive = 1;
            baby.type = 0;
            _Agents[slot] = baby;
        }}
    }}

    _Agents[id.x] = agent;
}}

[numthreads(256, 1, 1)]
void UpdatePredators(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _MaxPopulation) return;

    Agent agent = _Agents[id.x];
    if (agent.alive == 0 || agent.type != 1) return;

    uint rng = Hash(id.x + (uint)(_Time * 1000) + 999);

    // Chase nearest prey
    float3 chaseDir = float3(0, 0, 0);
    float closestPreyDist = 1e10;
    uint closestPreyIdx = 0;
    for (uint j = 0; j < _MaxPopulation; j++)
    {{
        if (_Agents[j].alive == 0 || _Agents[j].type != 0) continue;
        float3 diff = _Agents[j].position - agent.position;
        float dist = length(diff);
        if (dist < closestPreyDist)
        {{
            closestPreyDist = dist;
            chaseDir = normalize(diff);
            closestPreyIdx = j;
        }}
    }}

    // Move toward prey (or wander)
    if (closestPreyDist < 1e9)
        agent.velocity = chaseDir * 2.5;
    else
        agent.velocity = RandomDir(rng) * 1.5;

    agent.position += agent.velocity * _DeltaTime;

    // Boundary wrap
    float half = _WorldSize * 0.5;
    if (agent.position.x > half)  agent.position.x -= _WorldSize;
    if (agent.position.x < -half) agent.position.x += _WorldSize;
    if (agent.position.z > half)  agent.position.z -= _WorldSize;
    if (agent.position.z < -half) agent.position.z += _WorldSize;
    agent.position.y = 0;

    // Eat prey if close enough
    if (closestPreyDist < _CatchRadius)
    {{
        _Agents[closestPreyIdx].alive = 0;
        agent.energy += 5.0;
    }}

    // Starve
    agent.energy -= _PredatorDeathRate * _DeltaTime;
    if (agent.energy <= 0)
    {{
        agent.alive = 0;
    }}
    else if (agent.energy > 10.0)
    {{
        // Reproduce
        agent.energy *= 0.5;
        uint slot = Hash(rng + id.x + 777) % _MaxPopulation;
        if (_Agents[slot].alive == 0)
        {{
            Agent baby;
            baby.position = agent.position + RandomDir(Hash(slot)) * 1.0;
            baby.velocity = float3(0, 0, 0);
            baby.energy = agent.energy * 0.5;
            baby.alive = 1;
            baby.type = 1;
            _Agents[slot] = baby;
        }}
    }}

    _Agents[id.x] = agent;
}}
";
            File.WriteAllText(computeFullPath, computeContent);
            AssetDatabase.ImportAsset(computeAssetPath);

            // --- Manager Script ---
            string managerAssetPath = $"{outputDir}/EcosystemManager.cs";
            string managerFullPath  = Path.Combine(Application.dataPath, "..", managerAssetPath);
            string managerContent   = $@"// Generated by Mosaic Bridge - simulation/ecosystem
// Customize as needed

using UnityEngine;

public class EcosystemManager : MonoBehaviour
{{
    [Header(""Population"")]
    public int   preyCount            = {preyCount};
    public int   predatorCount        = {predatorCount};
    public int   maxPopulation        = {maxPopulation};
    public float preyReproductionRate = {preyReproductionRate}f;
    public float predatorDeathRate    = {predatorDeathRate}f;
    public float catchRadius          = {catchRadius}f;
    public float worldSize            = {worldSize}f;

    [Header(""Rendering"")]
    public ComputeShader computeShader;
    public Mesh          preyMesh;
    public Mesh          predatorMesh;
    public Material      preyMaterial;
    public Material      predatorMaterial;

    private ComputeBuffer _agentBuffer;
    private ComputeBuffer _preyArgsBuffer;
    private ComputeBuffer _predatorArgsBuffer;
    private int _kUpdatePrey;
    private int _kUpdatePredators;
    private int _threadGroups;

    struct Agent
    {{
        public Vector3 position;
        public Vector3 velocity;
        public float   energy;
        public int     alive;
        public int     type;
    }}

    void Start()
    {{
        _kUpdatePrey      = computeShader.FindKernel(""UpdatePrey"");
        _kUpdatePredators = computeShader.FindKernel(""UpdatePredators"");

        int stride = sizeof(float) * 8 + sizeof(int) * 2; // 3+3+1+1 floats + 2 ints
        _agentBuffer = new ComputeBuffer(maxPopulation, stride);

        var agents = new Agent[maxPopulation];
        int idx = 0;
        for (int i = 0; i < preyCount && idx < maxPopulation; i++, idx++)
        {{
            agents[idx].position = new Vector3(
                Random.Range(-worldSize * 0.5f, worldSize * 0.5f), 0,
                Random.Range(-worldSize * 0.5f, worldSize * 0.5f));
            agents[idx].energy = 0.5f;
            agents[idx].alive = 1;
            agents[idx].type = 0;
        }}
        for (int i = 0; i < predatorCount && idx < maxPopulation; i++, idx++)
        {{
            agents[idx].position = new Vector3(
                Random.Range(-worldSize * 0.5f, worldSize * 0.5f), 0,
                Random.Range(-worldSize * 0.5f, worldSize * 0.5f));
            agents[idx].energy = 5f;
            agents[idx].alive = 1;
            agents[idx].type = 1;
        }}
        _agentBuffer.SetData(agents);

        _threadGroups = Mathf.CeilToInt(maxPopulation / 256f);

        // Args buffers
        _preyArgsBuffer = new ComputeBuffer(1, 5 * sizeof(uint), ComputeBufferType.IndirectArguments);
        _predatorArgsBuffer = new ComputeBuffer(1, 5 * sizeof(uint), ComputeBufferType.IndirectArguments);
    }}

    void Update()
    {{
        computeShader.SetInt(""_MaxPopulation"", maxPopulation);
        computeShader.SetInt(""_PreyCount"", preyCount);
        computeShader.SetInt(""_PredatorCount"", predatorCount);
        computeShader.SetFloat(""_PreyReproductionRate"", preyReproductionRate);
        computeShader.SetFloat(""_PredatorDeathRate"", predatorDeathRate);
        computeShader.SetFloat(""_CatchRadius"", catchRadius);
        computeShader.SetFloat(""_WorldSize"", worldSize);
        computeShader.SetFloat(""_DeltaTime"", Time.deltaTime);
        computeShader.SetFloat(""_Time"", Time.time);

        computeShader.SetBuffer(_kUpdatePrey,      ""_Agents"", _agentBuffer);
        computeShader.SetBuffer(_kUpdatePredators,  ""_Agents"", _agentBuffer);

        computeShader.Dispatch(_kUpdatePrey,      _threadGroups, 1, 1);
        computeShader.Dispatch(_kUpdatePredators,  _threadGroups, 1, 1);

        // Render prey
        if (preyMesh != null && preyMaterial != null)
        {{
            preyMaterial.SetBuffer(""_Agents"", _agentBuffer);
            preyMaterial.SetInt(""_FilterType"", 0);
            Graphics.DrawMeshInstancedIndirect(preyMesh, 0, preyMaterial,
                new Bounds(Vector3.zero, Vector3.one * worldSize), _preyArgsBuffer);
        }}

        // Render predators
        if (predatorMesh != null && predatorMaterial != null)
        {{
            predatorMaterial.SetBuffer(""_Agents"", _agentBuffer);
            predatorMaterial.SetInt(""_FilterType"", 1);
            Graphics.DrawMeshInstancedIndirect(predatorMesh, 0, predatorMaterial,
                new Bounds(Vector3.zero, Vector3.one * worldSize), _predatorArgsBuffer);
        }}
    }}

    void OnDestroy()
    {{
        _agentBuffer?.Release();
        _preyArgsBuffer?.Release();
        _predatorArgsBuffer?.Release();
    }}
}}
";
            File.WriteAllText(managerFullPath, managerContent);
            AssetDatabase.ImportAsset(managerAssetPath);

            return ToolResult<SimEcosystemResult>.Ok(new SimEcosystemResult
            {
                ComputeShaderPath = computeAssetPath,
                ManagerScriptPath = managerAssetPath,
                PreyCount         = preyCount,
                PredatorCount     = predatorCount
            });
        }
    }
}
