using System.IO;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Tools.Shared;

namespace Mosaic.Bridge.Tools.Simulation
{
    public static class SimFluidTool
    {
        [MosaicTool("simulation/fluid",
                    "Generates an SPH fluid simulation compute shader and manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<SimFluidResult> Execute(SimFluidParams p)
        {
            int   particleCount   = p.ParticleCount   ?? 2048;
            float fluidDensity    = p.FluidDensity     ?? 997f;
            float viscosity       = p.Viscosity        ?? 0.1f;
            float gravity         = p.Gravity          ?? -9.81f;
            float smoothingRadius = p.SmoothingRadius  ?? 0.4f;
            float boundarySize    = p.BoundarySize     ?? 10f;

            if (particleCount < 1 || particleCount > 1048576)
                return ToolResult<SimFluidResult>.Fail(
                    "ParticleCount must be between 1 and 1048576", ErrorCodes.INVALID_PARAM);

            string outputDir = p.OutputDirectory ?? "Assets/Generated/Simulation/Fluid";
            if (!outputDir.StartsWith("Assets/"))
                return ToolResult<SimFluidResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            AssetDatabaseHelper.EnsureFolder(outputDir);
            string fullDir = Path.Combine(Application.dataPath, "..", outputDir);

            // --- Compute Shader ---
            string computeAssetPath = $"{outputDir}/FluidSPH.compute";
            string computeFullPath  = Path.Combine(Application.dataPath, "..", computeAssetPath);
            string computeContent   = $@"// Generated by Mosaic Bridge - simulation/fluid
// Customize as needed

#pragma kernel ComputeDensityPressure
#pragma kernel ComputeForces
#pragma kernel Integrate

struct Particle
{{
    float3 position;
    float3 velocity;
    float  density;
    float  pressure;
}};

RWStructuredBuffer<Particle> _Particles;

uint   _ParticleCount;
float  _RestDensity;    // {fluidDensity}
float  _Viscosity;      // {viscosity}
float  _Gravity;        // {gravity}
float  _SmoothingRadius;// {smoothingRadius}
float  _BoundarySize;   // {boundarySize}
float  _DeltaTime;
float  _GasConstant;
float  _Mass;

static const float PI = 3.14159265;

// Poly6 kernel
float Poly6(float r2, float h)
{{
    float h2 = h * h;
    if (r2 >= h2) return 0;
    float diff = h2 - r2;
    return 315.0 / (64.0 * PI * pow(h, 9)) * diff * diff * diff;
}}

// Spiky gradient kernel
float3 SpikyGrad(float3 r, float rLen, float h)
{{
    if (rLen >= h || rLen < 1e-6) return float3(0, 0, 0);
    float diff = h - rLen;
    return -45.0 / (PI * pow(h, 6)) * diff * diff * normalize(r);
}}

// Viscosity Laplacian kernel
float ViscLap(float r, float h)
{{
    if (r >= h) return 0;
    return 45.0 / (PI * pow(h, 6)) * (h - r);
}}

[numthreads(256, 1, 1)]
void ComputeDensityPressure(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _ParticleCount) return;

    float density = 0;
    float3 posI = _Particles[id.x].position;

    for (uint j = 0; j < _ParticleCount; j++)
    {{
        float3 diff = posI - _Particles[j].position;
        float r2 = dot(diff, diff);
        density += _Mass * Poly6(r2, _SmoothingRadius);
    }}

    _Particles[id.x].density  = density;
    _Particles[id.x].pressure = _GasConstant * (density - _RestDensity);
}}

[numthreads(256, 1, 1)]
void ComputeForces(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _ParticleCount) return;

    float3 posI   = _Particles[id.x].position;
    float3 velI   = _Particles[id.x].velocity;
    float  pressI = _Particles[id.x].pressure;
    float  densI  = _Particles[id.x].density;

    float3 fPressure  = float3(0, 0, 0);
    float3 fViscosity = float3(0, 0, 0);

    for (uint j = 0; j < _ParticleCount; j++)
    {{
        if (j == id.x) continue;
        float3 diff = posI - _Particles[j].position;
        float r = length(diff);

        // Pressure force
        fPressure += -normalize(diff) * _Mass *
            (pressI + _Particles[j].pressure) / (2.0 * _Particles[j].density) *
            length(SpikyGrad(diff, r, _SmoothingRadius));

        // Viscosity force
        fViscosity += _Viscosity * _Mass *
            (_Particles[j].velocity - velI) / _Particles[j].density *
            ViscLap(r, _SmoothingRadius);
    }}

    float3 fGravity = float3(0, _Gravity, 0) * densI;
    float3 totalForce = fPressure + fViscosity + fGravity;

    _Particles[id.x].velocity += totalForce / densI * _DeltaTime;
}}

[numthreads(256, 1, 1)]
void Integrate(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _ParticleCount) return;

    _Particles[id.x].position += _Particles[id.x].velocity * _DeltaTime;

    // Boundary enforcement
    float half = _BoundarySize * 0.5;
    float3 pos = _Particles[id.x].position;
    float3 vel = _Particles[id.x].velocity;

    if (pos.x < -half) {{ pos.x = -half; vel.x *= -0.5; }}
    if (pos.x >  half) {{ pos.x =  half; vel.x *= -0.5; }}
    if (pos.y < -half) {{ pos.y = -half; vel.y *= -0.5; }}
    if (pos.y >  half) {{ pos.y =  half; vel.y *= -0.5; }}
    if (pos.z < -half) {{ pos.z = -half; vel.z *= -0.5; }}
    if (pos.z >  half) {{ pos.z =  half; vel.z *= -0.5; }}

    _Particles[id.x].position = pos;
    _Particles[id.x].velocity = vel;
}}
";
            File.WriteAllText(computeFullPath, computeContent);
            AssetDatabase.ImportAsset(computeAssetPath);

            // --- Manager Script ---
            string managerAssetPath = $"{outputDir}/FluidSPHManager.cs";
            string managerFullPath  = Path.Combine(Application.dataPath, "..", managerAssetPath);
            string managerContent   = $@"// Generated by Mosaic Bridge - simulation/fluid
// Customize as needed

using UnityEngine;

public class FluidSPHManager : MonoBehaviour
{{
    [Header(""Simulation Parameters"")]
    public int   particleCount   = {particleCount};
    public float restDensity     = {fluidDensity}f;
    public float viscosity       = {viscosity}f;
    public float gravity         = {gravity}f;
    public float smoothingRadius = {smoothingRadius}f;
    public float boundarySize    = {boundarySize}f;
    public float gasConstant     = 2000f;
    public float mass            = 1f;

    [Header(""Rendering"")]
    public ComputeShader computeShader;
    public Mesh          particleMesh;
    public Material      particleMaterial;

    private ComputeBuffer _particleBuffer;
    private ComputeBuffer _argsBuffer;

    private int _kernelDensity;
    private int _kernelForces;
    private int _kernelIntegrate;
    private int _threadGroups;

    struct Particle
    {{
        public Vector3 position;
        public Vector3 velocity;
        public float   density;
        public float   pressure;
    }}

    void Start()
    {{
        _kernelDensity   = computeShader.FindKernel(""ComputeDensityPressure"");
        _kernelForces    = computeShader.FindKernel(""ComputeForces"");
        _kernelIntegrate = computeShader.FindKernel(""Integrate"");

        int stride = sizeof(float) * 8; // 3+3+1+1
        _particleBuffer = new ComputeBuffer(particleCount, stride);

        var particles = new Particle[particleCount];
        int perSide = Mathf.CeilToInt(Mathf.Pow(particleCount, 1f / 3f));
        float spacing = smoothingRadius * 0.5f;
        for (int i = 0; i < particleCount; i++)
        {{
            int x = i % perSide;
            int y = (i / perSide) % perSide;
            int z = i / (perSide * perSide);
            particles[i].position = new Vector3(x, y, z) * spacing - Vector3.one * (perSide * spacing * 0.5f);
            particles[i].velocity = Vector3.zero;
        }}
        _particleBuffer.SetData(particles);

        _threadGroups = Mathf.CeilToInt(particleCount / 256f);

        // Args buffer for DrawMeshInstancedIndirect
        _argsBuffer = new ComputeBuffer(1, 5 * sizeof(uint), ComputeBufferType.IndirectArguments);
        uint[] args = new uint[5];
        args[0] = particleMesh ? particleMesh.GetIndexCount(0) : 0;
        args[1] = (uint)particleCount;
        args[2] = particleMesh ? particleMesh.GetIndexStart(0) : 0;
        args[3] = particleMesh ? particleMesh.GetBaseVertex(0) : 0;
        args[4] = 0;
        _argsBuffer.SetData(args);
    }}

    void Update()
    {{
        float dt = Time.deltaTime;

        computeShader.SetInt(""_ParticleCount"", particleCount);
        computeShader.SetFloat(""_RestDensity"", restDensity);
        computeShader.SetFloat(""_Viscosity"", viscosity);
        computeShader.SetFloat(""_Gravity"", gravity);
        computeShader.SetFloat(""_SmoothingRadius"", smoothingRadius);
        computeShader.SetFloat(""_BoundarySize"", boundarySize);
        computeShader.SetFloat(""_DeltaTime"", dt);
        computeShader.SetFloat(""_GasConstant"", gasConstant);
        computeShader.SetFloat(""_Mass"", mass);

        computeShader.SetBuffer(_kernelDensity,   ""_Particles"", _particleBuffer);
        computeShader.SetBuffer(_kernelForces,    ""_Particles"", _particleBuffer);
        computeShader.SetBuffer(_kernelIntegrate, ""_Particles"", _particleBuffer);

        computeShader.Dispatch(_kernelDensity,   _threadGroups, 1, 1);
        computeShader.Dispatch(_kernelForces,    _threadGroups, 1, 1);
        computeShader.Dispatch(_kernelIntegrate, _threadGroups, 1, 1);

        // GPU instanced rendering
        if (particleMesh != null && particleMaterial != null)
        {{
            particleMaterial.SetBuffer(""_Particles"", _particleBuffer);
            Graphics.DrawMeshInstancedIndirect(particleMesh, 0, particleMaterial,
                new Bounds(Vector3.zero, Vector3.one * boundarySize), _argsBuffer);
        }}
    }}

    void OnDestroy()
    {{
        _particleBuffer?.Release();
        _argsBuffer?.Release();
    }}
}}
";
            File.WriteAllText(managerFullPath, managerContent);
            AssetDatabase.ImportAsset(managerAssetPath);

            return ToolResult<SimFluidResult>.Ok(new SimFluidResult
            {
                ComputeShaderPath = computeAssetPath,
                ManagerScriptPath = managerAssetPath,
                ParticleCount     = particleCount,
                FluidDensity      = fluidDensity
            });
        }
    }
}
