using System.IO;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;

namespace Mosaic.Bridge.Tools.Simulation
{
    public static class SimOrbitalTool
    {
        [MosaicTool("simulation/orbital",
                    "Generates an N-body gravitational simulation compute shader and manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<SimOrbitalResult> Execute(SimOrbitalParams p)
        {
            int   bodyCount   = p.BodyCount             ?? 100;
            float gravConst   = p.GravitationalConstant ?? 0.1f;
            float timeStep    = p.TimeStep              ?? 0.01f;
            float softening   = p.Softening             ?? 0.1f;
            float centralMass = p.CentralMass           ?? 1000f;
            float initRadius  = p.InitialRadius         ?? 20f;

            if (bodyCount < 2 || bodyCount > 2048)
                return ToolResult<SimOrbitalResult>.Fail(
                    "BodyCount must be between 2 and 2048", ErrorCodes.INVALID_PARAM);

            string outputDir = p.OutputDirectory ?? "Assets/Generated/Simulation/Orbital";
            if (!outputDir.StartsWith("Assets/"))
                return ToolResult<SimOrbitalResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            string fullDir = Path.Combine(Application.dataPath, "..", outputDir);
            Directory.CreateDirectory(fullDir);

            // --- Compute Shader ---
            string computeAssetPath = $"{outputDir}/NBody.compute";
            string computeFullPath  = Path.Combine(Application.dataPath, "..", computeAssetPath);
            string computeContent   = $@"// Generated by Mosaic Bridge - simulation/orbital
// Customize as needed

#pragma kernel ComputeForces
#pragma kernel Integrate

struct Body
{{
    float3 position;
    float3 velocity;
    float  mass;
}};

RWStructuredBuffer<Body> _Bodies;
RWStructuredBuffer<float3> _Accelerations;

uint   _BodyCount;
float  _G;          // {gravConst}
float  _Softening;  // {softening}
float  _DeltaTime;  // {timeStep}

[numthreads(256, 1, 1)]
void ComputeForces(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _BodyCount) return;

    float3 pos = _Bodies[id.x].position;
    float3 acc = float3(0, 0, 0);

    for (uint j = 0; j < _BodyCount; j++)
    {{
        if (j == id.x) continue;

        float3 diff = _Bodies[j].position - pos;
        float distSq = dot(diff, diff) + _Softening * _Softening;
        float invDist = rsqrt(distSq);
        float invDist3 = invDist * invDist * invDist;

        acc += _G * _Bodies[j].mass * diff * invDist3;
    }}

    _Accelerations[id.x] = acc;
}}

[numthreads(256, 1, 1)]
void Integrate(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _BodyCount) return;

    // Verlet-style integration
    float3 acc = _Accelerations[id.x];
    _Bodies[id.x].velocity += acc * _DeltaTime;
    _Bodies[id.x].position += _Bodies[id.x].velocity * _DeltaTime;
}}
";
            File.WriteAllText(computeFullPath, computeContent);
            AssetDatabase.ImportAsset(computeAssetPath);

            // --- Manager Script ---
            string managerAssetPath = $"{outputDir}/NBodyManager.cs";
            string managerFullPath  = Path.Combine(Application.dataPath, "..", managerAssetPath);
            string managerContent   = $@"// Generated by Mosaic Bridge - simulation/orbital
// Customize as needed

using UnityEngine;

public class NBodyManager : MonoBehaviour
{{
    [Header(""Simulation Parameters"")]
    public int   bodyCount   = {bodyCount};
    public float gravConst   = {gravConst}f;
    public float timeStep    = {timeStep}f;
    public float softening   = {softening}f;
    public float centralMass = {centralMass}f;
    public float initRadius  = {initRadius}f;

    [Header(""Rendering"")]
    public ComputeShader computeShader;
    public Mesh          bodyMesh;
    public Material      bodyMaterial;

    private ComputeBuffer _bodyBuffer;
    private ComputeBuffer _accelBuffer;
    private ComputeBuffer _argsBuffer;
    private int _kComputeForces;
    private int _kIntegrate;
    private int _threadGroups;

    struct Body
    {{
        public Vector3 position;
        public Vector3 velocity;
        public float   mass;
    }}

    void Start()
    {{
        _kComputeForces = computeShader.FindKernel(""ComputeForces"");
        _kIntegrate     = computeShader.FindKernel(""Integrate"");

        int bodyStride  = sizeof(float) * 7; // 3+3+1
        int accelStride = sizeof(float) * 3;

        _bodyBuffer  = new ComputeBuffer(bodyCount, bodyStride);
        _accelBuffer = new ComputeBuffer(bodyCount, accelStride);

        var bodies = new Body[bodyCount];

        // Central body
        bodies[0].position = Vector3.zero;
        bodies[0].velocity = Vector3.zero;
        bodies[0].mass     = centralMass;

        // Orbiting bodies
        for (int i = 1; i < bodyCount; i++)
        {{
            float angle  = Random.Range(0f, Mathf.PI * 2f);
            float radius = Random.Range(initRadius * 0.3f, initRadius);
            float inclination = Random.Range(-0.1f, 0.1f);

            bodies[i].position = new Vector3(
                Mathf.Cos(angle) * radius,
                inclination * radius,
                Mathf.Sin(angle) * radius);
            bodies[i].mass = Random.Range(0.1f, 5f);

            // Circular orbit velocity: v = sqrt(G*M/r)
            float orbitalSpeed = Mathf.Sqrt(gravConst * centralMass / radius);
            Vector3 tangent = new Vector3(-Mathf.Sin(angle), 0, Mathf.Cos(angle));
            bodies[i].velocity = tangent * orbitalSpeed;
        }}

        _bodyBuffer.SetData(bodies);

        _threadGroups = Mathf.CeilToInt(bodyCount / 256f);

        _argsBuffer = new ComputeBuffer(1, 5 * sizeof(uint), ComputeBufferType.IndirectArguments);
        uint[] args = new uint[5];
        args[0] = bodyMesh ? bodyMesh.GetIndexCount(0) : 0;
        args[1] = (uint)bodyCount;
        args[2] = bodyMesh ? bodyMesh.GetIndexStart(0) : 0;
        args[3] = bodyMesh ? bodyMesh.GetBaseVertex(0) : 0;
        args[4] = 0;
        _argsBuffer.SetData(args);
    }}

    void Update()
    {{
        computeShader.SetInt(""_BodyCount"", bodyCount);
        computeShader.SetFloat(""_G"", gravConst);
        computeShader.SetFloat(""_Softening"", softening);
        computeShader.SetFloat(""_DeltaTime"", timeStep);

        computeShader.SetBuffer(_kComputeForces, ""_Bodies"",        _bodyBuffer);
        computeShader.SetBuffer(_kComputeForces, ""_Accelerations"", _accelBuffer);
        computeShader.SetBuffer(_kIntegrate,     ""_Bodies"",        _bodyBuffer);
        computeShader.SetBuffer(_kIntegrate,     ""_Accelerations"", _accelBuffer);

        computeShader.Dispatch(_kComputeForces, _threadGroups, 1, 1);
        computeShader.Dispatch(_kIntegrate,     _threadGroups, 1, 1);

        if (bodyMesh != null && bodyMaterial != null)
        {{
            bodyMaterial.SetBuffer(""_Bodies"", _bodyBuffer);
            Graphics.DrawMeshInstancedIndirect(bodyMesh, 0, bodyMaterial,
                new Bounds(Vector3.zero, Vector3.one * initRadius * 4f), _argsBuffer);
        }}
    }}

    void OnDestroy()
    {{
        _bodyBuffer?.Release();
        _accelBuffer?.Release();
        _argsBuffer?.Release();
    }}
}}
";
            File.WriteAllText(managerFullPath, managerContent);
            AssetDatabase.ImportAsset(managerAssetPath);

            return ToolResult<SimOrbitalResult>.Ok(new SimOrbitalResult
            {
                ComputeShaderPath = computeAssetPath,
                ManagerScriptPath = managerAssetPath,
                BodyCount         = bodyCount
            });
        }
    }
}
