using System.IO;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;

namespace Mosaic.Bridge.Tools.Simulation
{
    public static class SimSmokeTool
    {
        [MosaicTool("simulation/smoke",
                    "Generates a Navier-Stokes smoke simulation compute shader and manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<SimSmokeResult> Execute(SimSmokeParams p)
        {
            int   resolution    = p.Resolution    ?? 256;
            float density       = p.Density       ?? 1f;
            float temperature   = p.Temperature   ?? 300f;
            float buoyancyForce = p.BuoyancyForce ?? 1f;
            float diffusionRate = p.DiffusionRate ?? 0.0001f;
            float timeStep      = p.TimeStep      ?? 0.1f;

            if (resolution < 16 || resolution > 2048)
                return ToolResult<SimSmokeResult>.Fail(
                    "Resolution must be between 16 and 2048", ErrorCodes.INVALID_PARAM);

            string outputDir = p.OutputDirectory ?? "Assets/Generated/Simulation/Smoke";
            if (!outputDir.StartsWith("Assets/"))
                return ToolResult<SimSmokeResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            string fullDir = Path.Combine(Application.dataPath, "..", outputDir);
            Directory.CreateDirectory(fullDir);

            // --- Compute Shader ---
            string computeAssetPath = $"{outputDir}/SmokeNavierStokes.compute";
            string computeFullPath  = Path.Combine(Application.dataPath, "..", computeAssetPath);
            string computeContent   = $@"// Generated by Mosaic Bridge - simulation/smoke
// Customize as needed

#pragma kernel Advect
#pragma kernel Diffuse
#pragma kernel AddForces
#pragma kernel ProjectDivergence
#pragma kernel ProjectPressure
#pragma kernel ProjectSubtract

uint _Resolution;  // {resolution}
float _DeltaTime;  // {timeStep}
float _Diffusion;  // {diffusionRate}
float _Buoyancy;   // {buoyancyForce}

RWTexture2D<float2> _VelocityIn;
RWTexture2D<float2> _VelocityOut;
RWTexture2D<float>  _DensityIn;
RWTexture2D<float>  _DensityOut;
RWTexture2D<float>  _Temperature;
RWTexture2D<float>  _Divergence;
RWTexture2D<float>  _PressureIn;
RWTexture2D<float>  _PressureOut;

float2 _InputPosition;
float  _InputRadius;
float  _InputDensityAmount;
float  _AmbientTemperature;

float2 SampleVelocityBilinear(float2 uv)
{{
    uint2 id = uint2(clamp(uv, 0, _Resolution - 1));
    return _VelocityIn[id];
}}

float SampleDensityBilinear(float2 uv)
{{
    uint2 id = uint2(clamp(uv, 0, _Resolution - 1));
    return _DensityIn[id];
}}

[numthreads(8, 8, 1)]
void Advect(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _Resolution || id.y >= _Resolution) return;

    float2 pos = float2(id.xy) - _DeltaTime * _VelocityIn[id.xy] * _Resolution;
    _VelocityOut[id.xy] = SampleVelocityBilinear(pos);
    _DensityOut[id.xy]  = SampleDensityBilinear(pos);
}}

[numthreads(8, 8, 1)]
void Diffuse(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _Resolution || id.y >= _Resolution) return;

    float a = _DeltaTime * _Diffusion * _Resolution * _Resolution;
    uint2 L = uint2(max(id.x - 1, 0), id.y);
    uint2 R = uint2(min(id.x + 1, _Resolution - 1), id.y);
    uint2 B = uint2(id.x, max(id.y - 1, 0));
    uint2 T = uint2(id.x, min(id.y + 1, _Resolution - 1));

    _DensityOut[id.xy] = (_DensityIn[id.xy] + a * (
        _DensityIn[L] + _DensityIn[R] + _DensityIn[B] + _DensityIn[T])) / (1.0 + 4.0 * a);
}}

[numthreads(8, 8, 1)]
void AddForces(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _Resolution || id.y >= _Resolution) return;

    // Buoyancy
    float temp = _Temperature[id.xy];
    float buoy = _Buoyancy * (temp - _AmbientTemperature) * _DeltaTime;
    float2 vel = _VelocityIn[id.xy];
    vel.y += buoy;

    // User input (add density at click position)
    float2 diff = float2(id.xy) / (float)_Resolution - _InputPosition;
    float dist = length(diff);
    if (dist < _InputRadius)
    {{
        float factor = 1.0 - dist / _InputRadius;
        _DensityOut[id.xy] = _DensityIn[id.xy] + _InputDensityAmount * factor * _DeltaTime;
        _Temperature[id.xy] = temp + _InputDensityAmount * factor * _DeltaTime * 10.0;
    }}

    _VelocityOut[id.xy] = vel;
}}

[numthreads(8, 8, 1)]
void ProjectDivergence(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _Resolution || id.y >= _Resolution) return;

    uint2 L = uint2(max(id.x - 1, 0), id.y);
    uint2 R = uint2(min(id.x + 1, _Resolution - 1), id.y);
    uint2 B = uint2(id.x, max(id.y - 1, 0));
    uint2 T = uint2(id.x, min(id.y + 1, _Resolution - 1));

    float div = -0.5 * (
        (_VelocityIn[R].x - _VelocityIn[L].x) +
        (_VelocityIn[T].y - _VelocityIn[B].y)) / _Resolution;

    _Divergence[id.xy] = div;
    _PressureOut[id.xy] = 0;
}}

[numthreads(8, 8, 1)]
void ProjectPressure(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _Resolution || id.y >= _Resolution) return;

    uint2 L = uint2(max(id.x - 1, 0), id.y);
    uint2 R = uint2(min(id.x + 1, _Resolution - 1), id.y);
    uint2 B = uint2(id.x, max(id.y - 1, 0));
    uint2 T = uint2(id.x, min(id.y + 1, _Resolution - 1));

    _PressureOut[id.xy] = (_Divergence[id.xy] +
        _PressureIn[L] + _PressureIn[R] + _PressureIn[B] + _PressureIn[T]) / 4.0;
}}

[numthreads(8, 8, 1)]
void ProjectSubtract(uint3 id : SV_DispatchThreadID)
{{
    if (id.x >= _Resolution || id.y >= _Resolution) return;

    uint2 L = uint2(max(id.x - 1, 0), id.y);
    uint2 R = uint2(min(id.x + 1, _Resolution - 1), id.y);
    uint2 B = uint2(id.x, max(id.y - 1, 0));
    uint2 T = uint2(id.x, min(id.y + 1, _Resolution - 1));

    float2 vel = _VelocityIn[id.xy];
    vel.x -= 0.5 * _Resolution * (_PressureIn[R] - _PressureIn[L]);
    vel.y -= 0.5 * _Resolution * (_PressureIn[T] - _PressureIn[B]);

    _VelocityOut[id.xy] = vel;
}}
";
            File.WriteAllText(computeFullPath, computeContent);
            AssetDatabase.ImportAsset(computeAssetPath);

            // --- Manager Script ---
            string managerAssetPath = $"{outputDir}/SmokeSimManager.cs";
            string managerFullPath  = Path.Combine(Application.dataPath, "..", managerAssetPath);
            string managerContent   = $@"// Generated by Mosaic Bridge - simulation/smoke
// Customize as needed

using UnityEngine;
using UnityEngine.UI;

public class SmokeSimManager : MonoBehaviour
{{
    [Header(""Simulation Parameters"")]
    public int   resolution    = {resolution};
    public float diffusionRate = {diffusionRate}f;
    public float buoyancyForce = {buoyancyForce}f;
    public float timeStep      = {timeStep}f;
    public float ambientTemp   = 20f;
    public int   jacobiIter    = 20;

    [Header(""Input"")]
    public float inputRadius        = 0.05f;
    public float inputDensityAmount = 10f;

    [Header(""References"")]
    public ComputeShader computeShader;
    public RawImage      displayImage;

    private RenderTexture _velocityA, _velocityB;
    private RenderTexture _densityA, _densityB;
    private RenderTexture _temperature;
    private RenderTexture _divergence;
    private RenderTexture _pressureA, _pressureB;

    private int _kAdvect, _kDiffuse, _kAddForces;
    private int _kProjectDiv, _kProjectPressure, _kProjectSub;

    RenderTexture CreateRT(RenderTextureFormat fmt)
    {{
        var rt = new RenderTexture(resolution, resolution, 0, fmt);
        rt.enableRandomWrite = true;
        rt.Create();
        return rt;
    }}

    void Start()
    {{
        _velocityA   = CreateRT(RenderTextureFormat.RGFloat);
        _velocityB   = CreateRT(RenderTextureFormat.RGFloat);
        _densityA    = CreateRT(RenderTextureFormat.RFloat);
        _densityB    = CreateRT(RenderTextureFormat.RFloat);
        _temperature = CreateRT(RenderTextureFormat.RFloat);
        _divergence  = CreateRT(RenderTextureFormat.RFloat);
        _pressureA   = CreateRT(RenderTextureFormat.RFloat);
        _pressureB   = CreateRT(RenderTextureFormat.RFloat);

        _kAdvect          = computeShader.FindKernel(""Advect"");
        _kDiffuse         = computeShader.FindKernel(""Diffuse"");
        _kAddForces       = computeShader.FindKernel(""AddForces"");
        _kProjectDiv      = computeShader.FindKernel(""ProjectDivergence"");
        _kProjectPressure = computeShader.FindKernel(""ProjectPressure"");
        _kProjectSub      = computeShader.FindKernel(""ProjectSubtract"");

        if (displayImage != null)
            displayImage.texture = _densityA;
    }}

    void Update()
    {{
        int groups = Mathf.CeilToInt(resolution / 8f);

        computeShader.SetInt(""_Resolution"", resolution);
        computeShader.SetFloat(""_DeltaTime"", timeStep);
        computeShader.SetFloat(""_Diffusion"", diffusionRate);
        computeShader.SetFloat(""_Buoyancy"", buoyancyForce);
        computeShader.SetFloat(""_AmbientTemperature"", ambientTemp);

        // Mouse input
        Vector2 inputPos = Vector2.zero;
        float inputAmount = 0;
        if (Input.GetMouseButton(0))
        {{
            Vector2 mouseUV = new Vector2(
                Input.mousePosition.x / Screen.width,
                Input.mousePosition.y / Screen.height);
            inputPos = mouseUV;
            inputAmount = inputDensityAmount;
        }}
        computeShader.SetVector(""_InputPosition"", inputPos);
        computeShader.SetFloat(""_InputRadius"", inputRadius);
        computeShader.SetFloat(""_InputDensityAmount"", inputAmount);

        // Advect
        computeShader.SetTexture(_kAdvect, ""_VelocityIn"",  _velocityA);
        computeShader.SetTexture(_kAdvect, ""_VelocityOut"", _velocityB);
        computeShader.SetTexture(_kAdvect, ""_DensityIn"",   _densityA);
        computeShader.SetTexture(_kAdvect, ""_DensityOut"",  _densityB);
        computeShader.Dispatch(_kAdvect, groups, groups, 1);
        Swap(ref _velocityA, ref _velocityB);
        Swap(ref _densityA,  ref _densityB);

        // Diffuse
        for (int i = 0; i < jacobiIter; i++)
        {{
            computeShader.SetTexture(_kDiffuse, ""_DensityIn"",  _densityA);
            computeShader.SetTexture(_kDiffuse, ""_DensityOut"", _densityB);
            computeShader.Dispatch(_kDiffuse, groups, groups, 1);
            Swap(ref _densityA, ref _densityB);
        }}

        // Add forces
        computeShader.SetTexture(_kAddForces, ""_VelocityIn"",  _velocityA);
        computeShader.SetTexture(_kAddForces, ""_VelocityOut"", _velocityB);
        computeShader.SetTexture(_kAddForces, ""_DensityIn"",   _densityA);
        computeShader.SetTexture(_kAddForces, ""_DensityOut"",  _densityB);
        computeShader.SetTexture(_kAddForces, ""_Temperature"", _temperature);
        computeShader.Dispatch(_kAddForces, groups, groups, 1);
        Swap(ref _velocityA, ref _velocityB);
        Swap(ref _densityA,  ref _densityB);

        // Project: divergence
        computeShader.SetTexture(_kProjectDiv, ""_VelocityIn"", _velocityA);
        computeShader.SetTexture(_kProjectDiv, ""_Divergence"",  _divergence);
        computeShader.SetTexture(_kProjectDiv, ""_PressureOut"", _pressureA);
        computeShader.Dispatch(_kProjectDiv, groups, groups, 1);

        // Project: Jacobi pressure solve
        for (int i = 0; i < jacobiIter; i++)
        {{
            computeShader.SetTexture(_kProjectPressure, ""_PressureIn"",  _pressureA);
            computeShader.SetTexture(_kProjectPressure, ""_PressureOut"", _pressureB);
            computeShader.SetTexture(_kProjectPressure, ""_Divergence"",  _divergence);
            computeShader.Dispatch(_kProjectPressure, groups, groups, 1);
            Swap(ref _pressureA, ref _pressureB);
        }}

        // Project: subtract pressure gradient
        computeShader.SetTexture(_kProjectSub, ""_VelocityIn"",  _velocityA);
        computeShader.SetTexture(_kProjectSub, ""_VelocityOut"", _velocityB);
        computeShader.SetTexture(_kProjectSub, ""_PressureIn"",  _pressureA);
        computeShader.Dispatch(_kProjectSub, groups, groups, 1);
        Swap(ref _velocityA, ref _velocityB);

        if (displayImage != null)
            displayImage.texture = _densityA;
    }}

    void Swap(ref RenderTexture a, ref RenderTexture b)
    {{
        var tmp = a; a = b; b = tmp;
    }}

    void OnDestroy()
    {{
        Destroy(_velocityA);   Destroy(_velocityB);
        Destroy(_densityA);    Destroy(_densityB);
        Destroy(_temperature);
        Destroy(_divergence);
        Destroy(_pressureA);   Destroy(_pressureB);
    }}
}}
";
            File.WriteAllText(managerFullPath, managerContent);
            AssetDatabase.ImportAsset(managerAssetPath);

            return ToolResult<SimSmokeResult>.Ok(new SimSmokeResult
            {
                ComputeShaderPath = computeAssetPath,
                ManagerScriptPath = managerAssetPath,
                Resolution        = resolution
            });
        }
    }
}
