using System.IO;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Tools.Shared;

namespace Mosaic.Bridge.Tools.Simulation
{
    public static class SimSphericalGravityTool
    {
        [MosaicTool("simulation/spherical-gravity",
                    "Generates spherical gravity scripts for walk-on-planet gameplay (CPU-based, no compute shader)",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<SimSphericalGravityResult> Execute(SimSphericalGravityParams p)
        {
            float gravityStrength = p.GravityStrength ?? 9.81f;
            float planetRadius    = p.PlanetRadius    ?? 50f;
            int   objectCount     = p.ObjectCount     ?? 10;

            if (planetRadius <= 0)
                return ToolResult<SimSphericalGravityResult>.Fail(
                    "PlanetRadius must be greater than 0", ErrorCodes.INVALID_PARAM);
            if (objectCount < 1 || objectCount > 1000)
                return ToolResult<SimSphericalGravityResult>.Fail(
                    "ObjectCount must be between 1 and 1000", ErrorCodes.INVALID_PARAM);

            string outputDir = p.OutputDirectory ?? "Assets/Generated/Simulation/SphericalGravity";
            if (!outputDir.StartsWith("Assets/"))
                return ToolResult<SimSphericalGravityResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            AssetDatabaseHelper.EnsureFolder(outputDir);
            string fullDir = Path.Combine(Application.dataPath, "..", outputDir);

            // --- GravityAttractor.cs ---
            string attractorAssetPath = $"{outputDir}/GravityAttractor.cs";
            string attractorFullPath  = Path.Combine(Application.dataPath, "..", attractorAssetPath);
            string attractorContent   = $@"// Generated by Mosaic Bridge - simulation/spherical-gravity
// Customize as needed

using UnityEngine;

public class GravityAttractor : MonoBehaviour
{{
    public float gravityStrength = {gravityStrength}f;

    public void Attract(Rigidbody body)
    {{
        Vector3 gravityUp = (body.position - transform.position).normalized;
        Vector3 localUp   = body.transform.up;

        // Apply gravity toward planet center
        body.AddForce(gravityUp * -gravityStrength, ForceMode.Acceleration);

        // Rotate body to align with surface normal
        Quaternion targetRotation = Quaternion.FromToRotation(localUp, gravityUp) * body.rotation;
        body.rotation = Quaternion.Slerp(body.rotation, targetRotation, 15f * Time.fixedDeltaTime);
    }}
}}
";
            File.WriteAllText(attractorFullPath, attractorContent);
            AssetDatabase.ImportAsset(attractorAssetPath);

            // --- GravityBody.cs ---
            string bodyAssetPath = $"{outputDir}/GravityBody.cs";
            string bodyFullPath  = Path.Combine(Application.dataPath, "..", bodyAssetPath);
            string bodyContent   = @"// Generated by Mosaic Bridge - simulation/spherical-gravity
// Customize as needed

using UnityEngine;

[RequireComponent(typeof(Rigidbody))]
public class GravityBody : MonoBehaviour
{
    private GravityAttractor _attractor;
    private Rigidbody _rb;

    void Awake()
    {
        _rb = GetComponent<Rigidbody>();
        _rb.useGravity = false;
        _rb.constraints = RigidbodyConstraints.FreezeRotation;
    }

    void Start()
    {
        FindNearestAttractor();
    }

    void FixedUpdate()
    {
        if (_attractor == null)
        {
            FindNearestAttractor();
            if (_attractor == null) return;
        }

        _attractor.Attract(_rb);
    }

    void FindNearestAttractor()
    {
        var attractors = FindObjectsByType<GravityAttractor>(FindObjectsSortMode.None);
        float closest = float.MaxValue;

        foreach (var attractor in attractors)
        {
            float dist = Vector3.Distance(transform.position, attractor.transform.position);
            if (dist < closest)
            {
                closest = dist;
                _attractor = attractor;
            }
        }
    }
}
";
            File.WriteAllText(bodyFullPath, bodyContent);
            AssetDatabase.ImportAsset(bodyAssetPath);

            // --- SphericalGravitySetup.cs ---
            string setupAssetPath = $"{outputDir}/SphericalGravitySetup.cs";
            string setupFullPath  = Path.Combine(Application.dataPath, "..", setupAssetPath);
            string setupContent   = $@"// Generated by Mosaic Bridge - simulation/spherical-gravity
// Customize as needed

using UnityEngine;

public class SphericalGravitySetup : MonoBehaviour
{{
    [Header(""Planet"")]
    public float planetRadius    = {planetRadius}f;
    public float gravityStrength = {gravityStrength}f;

    [Header(""Objects"")]
    public int   objectCount = {objectCount};
    public float objectSize  = 1f;

    [Header(""References"")]
    public Material planetMaterial;
    public Material objectMaterial;

    void Start()
    {{
        // Create planet
        var planet = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        planet.name = ""Planet"";
        planet.transform.localScale = Vector3.one * planetRadius * 2f;
        planet.transform.position = Vector3.zero;
        if (planetMaterial != null)
            planet.GetComponent<Renderer>().material = planetMaterial;

        var attractor = planet.AddComponent<GravityAttractor>();
        attractor.gravityStrength = gravityStrength;

        // Remove default collider, add a proper sphere collider
        var col = planet.GetComponent<SphereCollider>();
        if (col != null) col.radius = 0.5f; // already correct for unit sphere scaled

        // Create objects on surface
        for (int i = 0; i < objectCount; i++)
        {{
            var obj = GameObject.CreatePrimitive(PrimitiveType.Cube);
            obj.name = $""GravityObject_{{i}}"";
            obj.transform.localScale = Vector3.one * objectSize;

            // Place on surface
            Vector3 dir = Random.onUnitSphere;
            obj.transform.position = dir * (planetRadius + objectSize * 0.5f + 0.1f);
            obj.transform.up = dir;

            if (objectMaterial != null)
                obj.GetComponent<Renderer>().material = objectMaterial;

            var rb = obj.AddComponent<Rigidbody>();
            rb.mass = 1f;
            obj.AddComponent<GravityBody>();
        }}
    }}
}}
";
            File.WriteAllText(setupFullPath, setupContent);
            AssetDatabase.ImportAsset(setupAssetPath);

            return ToolResult<SimSphericalGravityResult>.Ok(new SimSphericalGravityResult
            {
                AttractorScriptPath = attractorAssetPath,
                BodyScriptPath      = bodyAssetPath,
                SetupScriptPath     = setupAssetPath,
                GravityStrength     = gravityStrength
            });
        }
    }
}
