using System.IO;
using System.Text;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Tools.Shared;

namespace Mosaic.Bridge.Tools.ProcGen
{
    public static class ProcGenPlanetTool
    {
        [MosaicTool("procgen/planet",
                    "Generates a subdivided sphere with noise-based terrain compute shader and manager",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<ProcGenPlanetResult> Execute(ProcGenPlanetParams p)
        {
            float radius     = p.Radius ?? 10f;
            int   resolution = Mathf.Clamp(p.Resolution ?? 64, 4, 256);
            float noiseScale = p.NoiseScale ?? 1f;
            float noiseStr   = p.NoiseStrength ?? 0.3f;
            int   octaves    = p.Octaves ?? 4;
            int   seed       = p.Seed ?? 0;
            string outDir    = p.OutputDirectory ?? "Assets/Generated/ProcGen/Planet";

            if (!outDir.StartsWith("Assets/"))
                return ToolResult<ProcGenPlanetResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            AssetDatabaseHelper.EnsureFolder(outDir);
            var fullDir = Path.Combine(Application.dataPath, "..", outDir);

            // --- Compute Shader ---
            string computeName  = "PlanetDeform.compute";
            string computeAsset = outDir + "/" + computeName;
            string computeFull  = Path.Combine(fullDir, computeName);

            var cs = new StringBuilder();
            cs.AppendLine("// Generated by Mosaic Bridge - procgen/planet");
            cs.AppendLine("#pragma kernel DeformSphere");
            cs.AppendLine();
            cs.AppendLine("RWStructuredBuffer<float3> vertices;");
            cs.AppendLine("RWStructuredBuffer<float3> normals;");
            cs.AppendLine("int _VertexCount;");
            cs.AppendLine("float _Radius;");
            cs.AppendLine("float _NoiseScale;");
            cs.AppendLine("float _NoiseStrength;");
            cs.AppendLine("int _Octaves;");
            cs.AppendLine("int _Seed;");
            cs.AppendLine();
            cs.AppendLine("float hash3(float3 p)");
            cs.AppendLine("{");
            cs.AppendLine("    p = frac(p * float3(0.1031, 0.1030, 0.0973));");
            cs.AppendLine("    p += dot(p, p.yzx + 33.33);");
            cs.AppendLine("    return frac((p.x + p.y) * p.z);");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("float noise3D(float3 p)");
            cs.AppendLine("{");
            cs.AppendLine("    float3 i = floor(p);");
            cs.AppendLine("    float3 f = frac(p);");
            cs.AppendLine("    float3 u = f * f * (3.0 - 2.0 * f);");
            cs.AppendLine("    float a = hash3(i + float3(0,0,0));");
            cs.AppendLine("    float b = hash3(i + float3(1,0,0));");
            cs.AppendLine("    float c = hash3(i + float3(0,1,0));");
            cs.AppendLine("    float d = hash3(i + float3(1,1,0));");
            cs.AppendLine("    float e = hash3(i + float3(0,0,1));");
            cs.AppendLine("    float f2 = hash3(i + float3(1,0,1));");
            cs.AppendLine("    float g = hash3(i + float3(0,1,1));");
            cs.AppendLine("    float h = hash3(i + float3(1,1,1));");
            cs.AppendLine("    float x1 = lerp(a, b, u.x);");
            cs.AppendLine("    float x2 = lerp(c, d, u.x);");
            cs.AppendLine("    float x3 = lerp(e, f2, u.x);");
            cs.AppendLine("    float x4 = lerp(g, h, u.x);");
            cs.AppendLine("    float y1 = lerp(x1, x2, u.y);");
            cs.AppendLine("    float y2 = lerp(x3, x4, u.y);");
            cs.AppendLine("    return lerp(y1, y2, u.z);");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("float fbm3D(float3 p, int octaves)");
            cs.AppendLine("{");
            cs.AppendLine("    float total = 0; float amp = 1; float freq = 1; float maxVal = 0;");
            cs.AppendLine("    for (int i = 0; i < octaves; i++)");
            cs.AppendLine("    {");
            cs.AppendLine("        total += noise3D(p * freq) * amp;");
            cs.AppendLine("        maxVal += amp; amp *= 0.5; freq *= 2.0;");
            cs.AppendLine("    }");
            cs.AppendLine("    return total / maxVal;");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("[numthreads(256,1,1)]");
            cs.AppendLine("void DeformSphere(uint3 id : SV_DispatchThreadID)");
            cs.AppendLine("{");
            cs.AppendLine("    if ((int)id.x >= _VertexCount) return;");
            cs.AppendLine("    float3 v = vertices[id.x];");
            cs.AppendLine("    float3 n = normals[id.x];");
            cs.AppendLine("    float3 samplePos = v * _NoiseScale + float3(_Seed, _Seed, _Seed);");
            cs.AppendLine("    float displacement = fbm3D(samplePos, _Octaves) * _NoiseStrength * _Radius;");
            cs.AppendLine("    vertices[id.x] = n * (_Radius + displacement);");
            cs.AppendLine("}");

            File.WriteAllText(computeFull, cs.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(computeAsset);

            // --- Manager Script ---
            string managerName  = "PlanetManager.cs";
            string managerAsset = outDir + "/" + managerName;
            string managerFull  = Path.Combine(fullDir, managerName);

            var ms = new StringBuilder();
            ms.AppendLine("// Generated by Mosaic Bridge - Customize as needed");
            ms.AppendLine("using UnityEngine;");
            ms.AppendLine("using System.Collections.Generic;");
            ms.AppendLine();
            ms.AppendLine("[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]");
            ms.AppendLine("public class PlanetManager : MonoBehaviour");
            ms.AppendLine("{");
            ms.AppendLine("    public ComputeShader computeShader;");
            ms.AppendLine($"    public float radius = {radius}f;");
            ms.AppendLine($"    public int resolution = {resolution};");
            ms.AppendLine($"    public float noiseScale = {noiseScale}f;");
            ms.AppendLine($"    public float noiseStrength = {noiseStr}f;");
            ms.AppendLine($"    public int octaves = {octaves};");
            ms.AppendLine($"    public int seed = {seed};");
            ms.AppendLine("    public Gradient colorGradient;");
            ms.AppendLine();
            ms.AppendLine("    void Start() { Generate(); }");
            ms.AppendLine();
            ms.AppendLine("    public void Generate()");
            ms.AppendLine("    {");
            ms.AppendLine("        Mesh mesh = CreateIcoSphere(radius, Mathf.Clamp(resolution / 16, 1, 6));");
            ms.AppendLine("        Vector3[] verts = mesh.vertices;");
            ms.AppendLine("        Vector3[] norms = mesh.normals;");
            ms.AppendLine("        int count = verts.Length;");
            ms.AppendLine();
            ms.AppendLine("        ComputeBuffer vertBuf = new ComputeBuffer(count, 12);");
            ms.AppendLine("        ComputeBuffer normBuf = new ComputeBuffer(count, 12);");
            ms.AppendLine("        vertBuf.SetData(verts);");
            ms.AppendLine("        normBuf.SetData(norms);");
            ms.AppendLine();
            ms.AppendLine("        int kernel = computeShader.FindKernel(\"DeformSphere\");");
            ms.AppendLine("        computeShader.SetBuffer(kernel, \"vertices\", vertBuf);");
            ms.AppendLine("        computeShader.SetBuffer(kernel, \"normals\", normBuf);");
            ms.AppendLine("        computeShader.SetInt(\"_VertexCount\", count);");
            ms.AppendLine("        computeShader.SetFloat(\"_Radius\", radius);");
            ms.AppendLine("        computeShader.SetFloat(\"_NoiseScale\", noiseScale);");
            ms.AppendLine("        computeShader.SetFloat(\"_NoiseStrength\", noiseStrength);");
            ms.AppendLine("        computeShader.SetInt(\"_Octaves\", octaves);");
            ms.AppendLine("        computeShader.SetInt(\"_Seed\", seed);");
            ms.AppendLine("        computeShader.Dispatch(kernel, Mathf.CeilToInt(count / 256f), 1, 1);");
            ms.AppendLine();
            ms.AppendLine("        vertBuf.GetData(verts);");
            ms.AppendLine("        vertBuf.Release();");
            ms.AppendLine("        normBuf.Release();");
            ms.AppendLine();
            ms.AppendLine("        mesh.vertices = verts;");
            ms.AppendLine("        mesh.RecalculateNormals();");
            ms.AppendLine("        mesh.RecalculateBounds();");
            ms.AppendLine();
            ms.AppendLine("        // Color by elevation");
            ms.AppendLine("        if (colorGradient != null)");
            ms.AppendLine("        {");
            ms.AppendLine("            Color[] colors = new Color[count];");
            ms.AppendLine("            float minH = float.MaxValue, maxH = float.MinValue;");
            ms.AppendLine("            for (int i = 0; i < count; i++)");
            ms.AppendLine("            {");
            ms.AppendLine("                float h = verts[i].magnitude;");
            ms.AppendLine("                if (h < minH) minH = h;");
            ms.AppendLine("                if (h > maxH) maxH = h;");
            ms.AppendLine("            }");
            ms.AppendLine("            for (int i = 0; i < count; i++)");
            ms.AppendLine("                colors[i] = colorGradient.Evaluate(Mathf.InverseLerp(minH, maxH, verts[i].magnitude));");
            ms.AppendLine("            mesh.colors = colors;");
            ms.AppendLine("        }");
            ms.AppendLine();
            ms.AppendLine("        GetComponent<MeshFilter>().mesh = mesh;");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    Mesh CreateIcoSphere(float r, int subdivisions)");
            ms.AppendLine("    {");
            ms.AppendLine("        // Simple UV sphere as a starting point");
            ms.AppendLine("        int lonSegments = 24 * subdivisions;");
            ms.AppendLine("        int latSegments = 12 * subdivisions;");
            ms.AppendLine("        var verts = new List<Vector3>();");
            ms.AppendLine("        var norms = new List<Vector3>();");
            ms.AppendLine("        var tris  = new List<int>();");
            ms.AppendLine("        for (int lat = 0; lat <= latSegments; lat++)");
            ms.AppendLine("        {");
            ms.AppendLine("            float theta = Mathf.PI * lat / latSegments;");
            ms.AppendLine("            for (int lon = 0; lon <= lonSegments; lon++)");
            ms.AppendLine("            {");
            ms.AppendLine("                float phi = 2 * Mathf.PI * lon / lonSegments;");
            ms.AppendLine("                Vector3 n = new Vector3(");
            ms.AppendLine("                    Mathf.Sin(theta) * Mathf.Cos(phi),");
            ms.AppendLine("                    Mathf.Cos(theta),");
            ms.AppendLine("                    Mathf.Sin(theta) * Mathf.Sin(phi));");
            ms.AppendLine("                verts.Add(n * r);");
            ms.AppendLine("                norms.Add(n);");
            ms.AppendLine("            }");
            ms.AppendLine("        }");
            ms.AppendLine("        for (int lat = 0; lat < latSegments; lat++)");
            ms.AppendLine("            for (int lon = 0; lon < lonSegments; lon++)");
            ms.AppendLine("            {");
            ms.AppendLine("                int c = lat * (lonSegments + 1) + lon;");
            ms.AppendLine("                int n = c + lonSegments + 1;");
            ms.AppendLine("                tris.Add(c); tris.Add(n); tris.Add(c + 1);");
            ms.AppendLine("                tris.Add(c + 1); tris.Add(n); tris.Add(n + 1);");
            ms.AppendLine("            }");
            ms.AppendLine("        Mesh m = new Mesh();");
            ms.AppendLine("        m.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;");
            ms.AppendLine("        m.SetVertices(verts);");
            ms.AppendLine("        m.SetNormals(norms);");
            ms.AppendLine("        m.SetTriangles(tris, 0);");
            ms.AppendLine("        return m;");
            ms.AppendLine("    }");
            ms.AppendLine("}");

            File.WriteAllText(managerFull, ms.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(managerAsset);

            return ToolResult<ProcGenPlanetResult>.Ok(new ProcGenPlanetResult
            {
                ComputeShaderPath = computeAsset,
                ManagerScriptPath = managerAsset,
                Radius     = radius,
                Resolution = resolution
            });
        }
    }
}
