using System.IO;
using System.Text;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Tools.Shared;

namespace Mosaic.Bridge.Tools.ProcGen
{
    public static class ProcGenCellularAutomataTool
    {
        [MosaicTool("procgen/cellular-automata",
                    "Generates a generic cellular automata compute shader (Game of Life + custom rules) and manager",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<ProcGenCellularAutomataResult> Execute(ProcGenCellularAutomataParams p)
        {
            int    width     = p.Width ?? 128;
            int    height    = p.Height ?? 128;
            string birth     = p.BirthRule ?? "3";
            string survival  = p.SurvivalRule ?? "23";
            float  density   = p.InitialDensity ?? 0.4f;
            int    seed      = p.Seed ?? 0;
            string outDir    = p.OutputDirectory ?? "Assets/Generated/ProcGen/CellularAutomata";

            if (!outDir.StartsWith("Assets/"))
                return ToolResult<ProcGenCellularAutomataResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            AssetDatabaseHelper.EnsureFolder(outDir);
            var fullDir = Path.Combine(Application.dataPath, "..", outDir);

            // Build birth/survival bitmasks for the shader
            int birthMask    = RuleToBitmask(birth);
            int survivalMask = RuleToBitmask(survival);

            // --- Compute Shader ---
            string computeName  = "CellularAutomata.compute";
            string computeAsset = outDir + "/" + computeName;
            string computeFull  = Path.Combine(fullDir, computeName);

            var cs = new StringBuilder();
            cs.AppendLine("// Generated by Mosaic Bridge - procgen/cellular-automata");
            cs.AppendLine("#pragma kernel StepCA");
            cs.AppendLine();
            cs.AppendLine("RWTexture2D<float> _WriteMap;");
            cs.AppendLine("Texture2D<float> _ReadMap;");
            cs.AppendLine("int _Width;");
            cs.AppendLine("int _Height;");
            cs.AppendLine("int _BirthMask;");
            cs.AppendLine("int _SurvivalMask;");
            cs.AppendLine();
            cs.AppendLine("[numthreads(8,8,1)]");
            cs.AppendLine("void StepCA(uint3 id : SV_DispatchThreadID)");
            cs.AppendLine("{");
            cs.AppendLine("    if ((int)id.x >= _Width || (int)id.y >= _Height) return;");
            cs.AppendLine();
            cs.AppendLine("    int neighbours = 0;");
            cs.AppendLine("    for (int dy = -1; dy <= 1; dy++)");
            cs.AppendLine("        for (int dx = -1; dx <= 1; dx++)");
            cs.AppendLine("        {");
            cs.AppendLine("            if (dx == 0 && dy == 0) continue;");
            cs.AppendLine("            int nx = ((int)id.x + dx + _Width) % _Width;");
            cs.AppendLine("            int ny = ((int)id.y + dy + _Height) % _Height;");
            cs.AppendLine("            neighbours += _ReadMap[int2(nx, ny)] > 0.5 ? 1 : 0;");
            cs.AppendLine("        }");
            cs.AppendLine();
            cs.AppendLine("    float current = _ReadMap[id.xy];");
            cs.AppendLine("    int bit = 1 << neighbours;");
            cs.AppendLine("    if (current > 0.5)");
            cs.AppendLine("        _WriteMap[id.xy] = (_SurvivalMask & bit) != 0 ? 1.0 : 0.0;");
            cs.AppendLine("    else");
            cs.AppendLine("        _WriteMap[id.xy] = (_BirthMask & bit) != 0 ? 1.0 : 0.0;");
            cs.AppendLine("}");

            File.WriteAllText(computeFull, cs.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(computeAsset);

            // --- Manager Script ---
            string managerName  = "CellularAutomataManager.cs";
            string managerAsset = outDir + "/" + managerName;
            string managerFull  = Path.Combine(fullDir, managerName);

            var ms = new StringBuilder();
            ms.AppendLine("// Generated by Mosaic Bridge - Customize as needed");
            ms.AppendLine("using UnityEngine;");
            ms.AppendLine("using UnityEngine.UI;");
            ms.AppendLine();
            ms.AppendLine("public class CellularAutomataManager : MonoBehaviour");
            ms.AppendLine("{");
            ms.AppendLine("    public ComputeShader computeShader;");
            ms.AppendLine($"    public int width = {width};");
            ms.AppendLine($"    public int height = {height};");
            ms.AppendLine($"    public string birthRule = \"{birth}\";");
            ms.AppendLine($"    public string survivalRule = \"{survival}\";");
            ms.AppendLine($"    public float initialDensity = {density}f;");
            ms.AppendLine($"    public int seed = {seed};");
            ms.AppendLine("    public float stepInterval = 0.1f;");
            ms.AppendLine();
            ms.AppendLine("    RenderTexture rtA;");
            ms.AppendLine("    RenderTexture rtB;");
            ms.AppendLine("    bool pingPong;");
            ms.AppendLine("    float timer;");
            ms.AppendLine();
            ms.AppendLine("    void Start()");
            ms.AppendLine("    {");
            ms.AppendLine("        rtA = CreateRT();");
            ms.AppendLine("        rtB = CreateRT();");
            ms.AppendLine("        InitRandom();");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    RenderTexture CreateRT()");
            ms.AppendLine("    {");
            ms.AppendLine("        var rt = new RenderTexture(width, height, 0, RenderTextureFormat.RFloat);");
            ms.AppendLine("        rt.enableRandomWrite = true;");
            ms.AppendLine("        rt.filterMode = FilterMode.Point;");
            ms.AppendLine("        rt.Create();");
            ms.AppendLine("        return rt;");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void InitRandom()");
            ms.AppendLine("    {");
            ms.AppendLine("        Random.InitState(seed);");
            ms.AppendLine("        Texture2D tex = new Texture2D(width, height, TextureFormat.RFloat, false);");
            ms.AppendLine("        for (int y = 0; y < height; y++)");
            ms.AppendLine("            for (int x = 0; x < width; x++)");
            ms.AppendLine("                tex.SetPixel(x, y, new Color(Random.value < initialDensity ? 1f : 0f, 0, 0));");
            ms.AppendLine("        tex.Apply();");
            ms.AppendLine("        Graphics.Blit(tex, rtA);");
            ms.AppendLine("        Destroy(tex);");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void Update()");
            ms.AppendLine("    {");
            ms.AppendLine("        timer += Time.deltaTime;");
            ms.AppendLine("        if (timer < stepInterval) return;");
            ms.AppendLine("        timer = 0;");
            ms.AppendLine("        Step();");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void Step()");
            ms.AppendLine("    {");
            ms.AppendLine("        var read  = pingPong ? rtB : rtA;");
            ms.AppendLine("        var write = pingPong ? rtA : rtB;");
            ms.AppendLine("        pingPong = !pingPong;");
            ms.AppendLine();
            ms.AppendLine("        int kernel = computeShader.FindKernel(\"StepCA\");");
            ms.AppendLine("        computeShader.SetTexture(kernel, \"_ReadMap\", read);");
            ms.AppendLine("        computeShader.SetTexture(kernel, \"_WriteMap\", write);");
            ms.AppendLine("        computeShader.SetInt(\"_Width\", width);");
            ms.AppendLine("        computeShader.SetInt(\"_Height\", height);");
            ms.AppendLine("        computeShader.SetInt(\"_BirthMask\", RuleToBitmask(birthRule));");
            ms.AppendLine("        computeShader.SetInt(\"_SurvivalMask\", RuleToBitmask(survivalRule));");
            ms.AppendLine("        computeShader.Dispatch(kernel, Mathf.CeilToInt(width / 8f), Mathf.CeilToInt(height / 8f), 1);");
            ms.AppendLine();
            ms.AppendLine("        var rawImage = GetComponent<RawImage>();");
            ms.AppendLine("        if (rawImage != null) rawImage.texture = write;");
            ms.AppendLine("        var renderer = GetComponent<Renderer>();");
            ms.AppendLine("        if (renderer != null) renderer.material.mainTexture = write;");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    static int RuleToBitmask(string rule)");
            ms.AppendLine("    {");
            ms.AppendLine("        int mask = 0;");
            ms.AppendLine("        foreach (char c in rule)");
            ms.AppendLine("            if (c >= '0' && c <= '8')");
            ms.AppendLine("                mask |= 1 << (c - '0');");
            ms.AppendLine("        return mask;");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void OnDestroy()");
            ms.AppendLine("    {");
            ms.AppendLine("        if (rtA != null) rtA.Release();");
            ms.AppendLine("        if (rtB != null) rtB.Release();");
            ms.AppendLine("    }");
            ms.AppendLine("}");

            File.WriteAllText(managerFull, ms.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(managerAsset);

            return ToolResult<ProcGenCellularAutomataResult>.Ok(new ProcGenCellularAutomataResult
            {
                ComputeShaderPath = computeAsset,
                ManagerScriptPath = managerAsset,
                Width        = width,
                Height       = height,
                BirthRule    = birth,
                SurvivalRule = survival
            });
        }

        static int RuleToBitmask(string rule)
        {
            int mask = 0;
            foreach (char c in rule)
                if (c >= '0' && c <= '8')
                    mask |= 1 << (c - '0');
            return mask;
        }
    }
}
