using System.IO;
using System.Text;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Tools.Shared;

namespace Mosaic.Bridge.Tools.ProcGen
{
    public static class ProcGenPoissonSampleTool
    {
        [MosaicTool("procgen/poisson-sample",
                    "Generates a Poisson disc sampling script using Bridson's algorithm",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<ProcGenPoissonSampleResult> Execute(ProcGenPoissonSampleParams p)
        {
            if (p.Radius <= 0)
                return ToolResult<ProcGenPoissonSampleResult>.Fail(
                    "Radius must be greater than 0", ErrorCodes.INVALID_PARAM);

            float radius     = p.Radius;
            float regionW    = p.RegionWidth ?? 100f;
            float regionH    = p.RegionHeight ?? 100f;
            int   rejection  = p.RejectionSamples ?? 30;
            int   seed       = p.Seed ?? 0;
            string outDir    = p.OutputDirectory ?? "Assets/Generated/ProcGen/PoissonSample";

            if (!outDir.StartsWith("Assets/"))
                return ToolResult<ProcGenPoissonSampleResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            AssetDatabaseHelper.EnsureFolder(outDir);
            var fullDir = Path.Combine(Application.dataPath, "..", outDir);

            // --- Script only (no compute shader) ---
            string scriptName  = "PoissonSampler.cs";
            string scriptAsset = outDir + "/" + scriptName;
            string scriptFull  = Path.Combine(fullDir, scriptName);

            var sb = new StringBuilder();
            sb.AppendLine("// Generated by Mosaic Bridge - Customize as needed");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("public class PoissonSampler : MonoBehaviour");
            sb.AppendLine("{");
            sb.AppendLine($"    public float radius = {radius}f;");
            sb.AppendLine($"    public float regionWidth = {regionW}f;");
            sb.AppendLine($"    public float regionHeight = {regionH}f;");
            sb.AppendLine($"    public int rejectionSamples = {rejection};");
            sb.AppendLine($"    public int seed = {seed};");
            sb.AppendLine("    public GameObject prefab;");
            sb.AppendLine("    public bool debugSpheres = true;");
            sb.AppendLine("    public float debugSphereRadius = 0.5f;");
            sb.AppendLine();
            sb.AppendLine("    void Start() { Generate(); }");
            sb.AppendLine();
            sb.AppendLine("    public void Generate()");
            sb.AppendLine("    {");
            sb.AppendLine("        List<Vector2> points = GeneratePoints(radius, new Vector2(regionWidth, regionHeight), rejectionSamples);");
            sb.AppendLine("        foreach (var pt in points)");
            sb.AppendLine("        {");
            sb.AppendLine("            Vector3 pos = new Vector3(pt.x, 0, pt.y) + transform.position;");
            sb.AppendLine("            if (prefab != null)");
            sb.AppendLine("                Instantiate(prefab, pos, Quaternion.identity, transform);");
            sb.AppendLine("            else if (debugSpheres)");
            sb.AppendLine("            {");
            sb.AppendLine("                var go = GameObject.CreatePrimitive(PrimitiveType.Sphere);");
            sb.AppendLine("                go.transform.position = pos;");
            sb.AppendLine("                go.transform.localScale = Vector3.one * debugSphereRadius;");
            sb.AppendLine("                go.transform.SetParent(transform);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    // Bridson's algorithm for Poisson disc sampling");
            sb.AppendLine("    List<Vector2> GeneratePoints(float r, Vector2 regionSize, int numSamplesBeforeRejection)");
            sb.AppendLine("    {");
            sb.AppendLine("        Random.InitState(seed);");
            sb.AppendLine("        float cellSize = r / Mathf.Sqrt(2);");
            sb.AppendLine("        int gridW = Mathf.CeilToInt(regionSize.x / cellSize);");
            sb.AppendLine("        int gridH = Mathf.CeilToInt(regionSize.y / cellSize);");
            sb.AppendLine("        int[,] grid = new int[gridW, gridH];");
            sb.AppendLine("        for (int x = 0; x < gridW; x++)");
            sb.AppendLine("            for (int y = 0; y < gridH; y++)");
            sb.AppendLine("                grid[x, y] = -1;");
            sb.AppendLine();
            sb.AppendLine("        List<Vector2> points = new List<Vector2>();");
            sb.AppendLine("        List<int> spawnPoints = new List<int>();");
            sb.AppendLine();
            sb.AppendLine("        Vector2 firstPoint = regionSize / 2;");
            sb.AppendLine("        points.Add(firstPoint);");
            sb.AppendLine("        spawnPoints.Add(0);");
            sb.AppendLine("        grid[(int)(firstPoint.x / cellSize), (int)(firstPoint.y / cellSize)] = 0;");
            sb.AppendLine();
            sb.AppendLine("        while (spawnPoints.Count > 0)");
            sb.AppendLine("        {");
            sb.AppendLine("            int spawnIndex = Random.Range(0, spawnPoints.Count);");
            sb.AppendLine("            Vector2 spawnCenter = points[spawnPoints[spawnIndex]];");
            sb.AppendLine("            bool accepted = false;");
            sb.AppendLine();
            sb.AppendLine("            for (int i = 0; i < numSamplesBeforeRejection; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                float angle = Random.value * Mathf.PI * 2;");
            sb.AppendLine("                float dist = Random.Range(r, 2 * r);");
            sb.AppendLine("                Vector2 candidate = spawnCenter + new Vector2(Mathf.Cos(angle), Mathf.Sin(angle)) * dist;");
            sb.AppendLine();
            sb.AppendLine("                if (candidate.x >= 0 && candidate.x < regionSize.x &&");
            sb.AppendLine("                    candidate.y >= 0 && candidate.y < regionSize.y)");
            sb.AppendLine("                {");
            sb.AppendLine("                    int cellX = (int)(candidate.x / cellSize);");
            sb.AppendLine("                    int cellY = (int)(candidate.y / cellSize);");
            sb.AppendLine("                    bool valid = true;");
            sb.AppendLine();
            sb.AppendLine("                    for (int dx = -2; dx <= 2 && valid; dx++)");
            sb.AppendLine("                        for (int dy = -2; dy <= 2 && valid; dy++)");
            sb.AppendLine("                        {");
            sb.AppendLine("                            int nx = cellX + dx;");
            sb.AppendLine("                            int ny = cellY + dy;");
            sb.AppendLine("                            if (nx >= 0 && nx < gridW && ny >= 0 && ny < gridH && grid[nx, ny] != -1)");
            sb.AppendLine("                            {");
            sb.AppendLine("                                if ((candidate - points[grid[nx, ny]]).sqrMagnitude < r * r)");
            sb.AppendLine("                                    valid = false;");
            sb.AppendLine("                            }");
            sb.AppendLine("                        }");
            sb.AppendLine();
            sb.AppendLine("                    if (valid)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        int idx = points.Count;");
            sb.AppendLine("                        points.Add(candidate);");
            sb.AppendLine("                        spawnPoints.Add(idx);");
            sb.AppendLine("                        grid[cellX, cellY] = idx;");
            sb.AppendLine("                        accepted = true;");
            sb.AppendLine("                        break;");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            if (!accepted)");
            sb.AppendLine("                spawnPoints.RemoveAt(spawnIndex);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        return points;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(scriptFull, sb.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(scriptAsset);

            return ToolResult<ProcGenPoissonSampleResult>.Ok(new ProcGenPoissonSampleResult
            {
                ScriptPath   = scriptAsset,
                Radius       = radius,
                RegionWidth  = regionW,
                RegionHeight = regionH
            });
        }
    }
}
