using System.IO;
using System.Text;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;

namespace Mosaic.Bridge.Tools.ProcGen
{
    public static class ProcGenReactionDiffusionTool
    {
        [MosaicTool("procgen/reaction-diffusion",
                    "Generates a Gray-Scott reaction-diffusion simulation compute shader and manager",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<ProcGenReactionDiffusionResult> Execute(ProcGenReactionDiffusionParams p)
        {
            int   width  = p.Width ?? 256;
            int   height = p.Height ?? 256;
            float feed   = p.FeedRate ?? 0.055f;
            float kill   = p.KillRate ?? 0.062f;
            float diffA  = p.DiffusionRateA ?? 1.0f;
            float diffB  = p.DiffusionRateB ?? 0.5f;
            float dt     = p.DeltaTime ?? 1.0f;
            string outDir = p.OutputDirectory ?? "Assets/Generated/ProcGen/ReactionDiffusion";

            if (!outDir.StartsWith("Assets/"))
                return ToolResult<ProcGenReactionDiffusionResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            var fullDir = Path.Combine(Application.dataPath, "..", outDir);
            Directory.CreateDirectory(fullDir);

            // --- Compute Shader ---
            string computeName  = "ReactionDiffusion.compute";
            string computeAsset = outDir + "/" + computeName;
            string computeFull  = Path.Combine(fullDir, computeName);

            var cs = new StringBuilder();
            cs.AppendLine("// Generated by Mosaic Bridge - procgen/reaction-diffusion");
            cs.AppendLine("#pragma kernel Step");
            cs.AppendLine();
            cs.AppendLine("RWTexture2D<float2> _WriteMap;");
            cs.AppendLine("Texture2D<float2> _ReadMap;");
            cs.AppendLine("int _Width;");
            cs.AppendLine("int _Height;");
            cs.AppendLine("float _FeedRate;");
            cs.AppendLine("float _KillRate;");
            cs.AppendLine("float _DiffusionRateA;");
            cs.AppendLine("float _DiffusionRateB;");
            cs.AppendLine("float _DeltaTime;");
            cs.AppendLine();
            cs.AppendLine("float2 sampleWrap(int2 pos)");
            cs.AppendLine("{");
            cs.AppendLine("    pos.x = (pos.x + _Width) % _Width;");
            cs.AppendLine("    pos.y = (pos.y + _Height) % _Height;");
            cs.AppendLine("    return _ReadMap[pos];");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("[numthreads(8,8,1)]");
            cs.AppendLine("void Step(uint3 id : SV_DispatchThreadID)");
            cs.AppendLine("{");
            cs.AppendLine("    if ((int)id.x >= _Width || (int)id.y >= _Height) return;");
            cs.AppendLine("    int2 pos = int2(id.xy);");
            cs.AppendLine("    float2 center = _ReadMap[pos];");
            cs.AppendLine("    float a = center.x;");
            cs.AppendLine("    float b = center.y;");
            cs.AppendLine();
            cs.AppendLine("    // 2D Laplacian (5-point stencil)");
            cs.AppendLine("    float2 lap = -4.0 * center");
            cs.AppendLine("        + sampleWrap(pos + int2(1, 0))");
            cs.AppendLine("        + sampleWrap(pos + int2(-1, 0))");
            cs.AppendLine("        + sampleWrap(pos + int2(0, 1))");
            cs.AppendLine("        + sampleWrap(pos + int2(0, -1));");
            cs.AppendLine();
            cs.AppendLine("    float abb = a * b * b;");
            cs.AppendLine("    float newA = a + (_DiffusionRateA * lap.x - abb + _FeedRate * (1.0 - a)) * _DeltaTime;");
            cs.AppendLine("    float newB = b + (_DiffusionRateB * lap.y + abb - (_KillRate + _FeedRate) * b) * _DeltaTime;");
            cs.AppendLine();
            cs.AppendLine("    _WriteMap[pos] = float2(saturate(newA), saturate(newB));");
            cs.AppendLine("}");

            File.WriteAllText(computeFull, cs.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(computeAsset);

            // --- Manager Script ---
            string managerName  = "ReactionDiffusionManager.cs";
            string managerAsset = outDir + "/" + managerName;
            string managerFull  = Path.Combine(fullDir, managerName);

            var ms = new StringBuilder();
            ms.AppendLine("// Generated by Mosaic Bridge - Customize as needed");
            ms.AppendLine("using UnityEngine;");
            ms.AppendLine("using UnityEngine.UI;");
            ms.AppendLine();
            ms.AppendLine("public class ReactionDiffusionManager : MonoBehaviour");
            ms.AppendLine("{");
            ms.AppendLine("    public ComputeShader computeShader;");
            ms.AppendLine($"    public int width = {width};");
            ms.AppendLine($"    public int height = {height};");
            ms.AppendLine($"    public float feedRate = {feed}f;");
            ms.AppendLine($"    public float killRate = {kill}f;");
            ms.AppendLine($"    public float diffusionRateA = {diffA}f;");
            ms.AppendLine($"    public float diffusionRateB = {diffB}f;");
            ms.AppendLine($"    public float deltaTime = {dt}f;");
            ms.AppendLine("    public int stepsPerFrame = 8;");
            ms.AppendLine("    public Color colorA = Color.white;");
            ms.AppendLine("    public Color colorB = Color.black;");
            ms.AppendLine();
            ms.AppendLine("    RenderTexture rtA;");
            ms.AppendLine("    RenderTexture rtB;");
            ms.AppendLine("    Texture2D displayTex;");
            ms.AppendLine("    bool pingPong;");
            ms.AppendLine();
            ms.AppendLine("    void Start()");
            ms.AppendLine("    {");
            ms.AppendLine("        rtA = CreateRT();");
            ms.AppendLine("        rtB = CreateRT();");
            ms.AppendLine("        displayTex = new Texture2D(width, height, TextureFormat.RGBAFloat, false);");
            ms.AppendLine("        Init();");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    RenderTexture CreateRT()");
            ms.AppendLine("    {");
            ms.AppendLine("        var rt = new RenderTexture(width, height, 0, RenderTextureFormat.RGFloat);");
            ms.AppendLine("        rt.enableRandomWrite = true;");
            ms.AppendLine("        rt.filterMode = FilterMode.Bilinear;");
            ms.AppendLine("        rt.Create();");
            ms.AppendLine("        return rt;");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void Init()");
            ms.AppendLine("    {");
            ms.AppendLine("        // Fill with A=1, B=0, then seed a small region with B=1");
            ms.AppendLine("        Texture2D initTex = new Texture2D(width, height, TextureFormat.RGFloat, false);");
            ms.AppendLine("        for (int y = 0; y < height; y++)");
            ms.AppendLine("            for (int x = 0; x < width; x++)");
            ms.AppendLine("                initTex.SetPixel(x, y, new Color(1, 0, 0, 0));");
            ms.AppendLine("        // Seed center region");
            ms.AppendLine("        int cx = width / 2, cy = height / 2, r = Mathf.Max(width, height) / 20;");
            ms.AppendLine("        for (int y = cy - r; y <= cy + r; y++)");
            ms.AppendLine("            for (int x = cx - r; x <= cx + r; x++)");
            ms.AppendLine("                if (x >= 0 && x < width && y >= 0 && y < height)");
            ms.AppendLine("                    initTex.SetPixel(x, y, new Color(1, 1, 0, 0));");
            ms.AppendLine("        initTex.Apply();");
            ms.AppendLine("        Graphics.Blit(initTex, rtA);");
            ms.AppendLine("        Destroy(initTex);");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void Update()");
            ms.AppendLine("    {");
            ms.AppendLine("        int kernel = computeShader.FindKernel(\"Step\");");
            ms.AppendLine("        computeShader.SetInt(\"_Width\", width);");
            ms.AppendLine("        computeShader.SetInt(\"_Height\", height);");
            ms.AppendLine("        computeShader.SetFloat(\"_FeedRate\", feedRate);");
            ms.AppendLine("        computeShader.SetFloat(\"_KillRate\", killRate);");
            ms.AppendLine("        computeShader.SetFloat(\"_DiffusionRateA\", diffusionRateA);");
            ms.AppendLine("        computeShader.SetFloat(\"_DiffusionRateB\", diffusionRateB);");
            ms.AppendLine("        computeShader.SetFloat(\"_DeltaTime\", deltaTime);");
            ms.AppendLine("        int gx = Mathf.CeilToInt(width / 8f);");
            ms.AppendLine("        int gy = Mathf.CeilToInt(height / 8f);");
            ms.AppendLine();
            ms.AppendLine("        for (int i = 0; i < stepsPerFrame; i++)");
            ms.AppendLine("        {");
            ms.AppendLine("            var read  = pingPong ? rtB : rtA;");
            ms.AppendLine("            var write = pingPong ? rtA : rtB;");
            ms.AppendLine("            pingPong = !pingPong;");
            ms.AppendLine("            computeShader.SetTexture(kernel, \"_ReadMap\", read);");
            ms.AppendLine("            computeShader.SetTexture(kernel, \"_WriteMap\", write);");
            ms.AppendLine("            computeShader.Dispatch(kernel, gx, gy, 1);");
            ms.AppendLine("        }");
            ms.AppendLine();
            ms.AppendLine("        // Visualize");
            ms.AppendLine("        var result = pingPong ? rtB : rtA;");
            ms.AppendLine("        var rawImage = GetComponent<RawImage>();");
            ms.AppendLine("        if (rawImage != null) rawImage.texture = result;");
            ms.AppendLine("        var renderer = GetComponent<Renderer>();");
            ms.AppendLine("        if (renderer != null) renderer.material.mainTexture = result;");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void OnDestroy()");
            ms.AppendLine("    {");
            ms.AppendLine("        if (rtA != null) rtA.Release();");
            ms.AppendLine("        if (rtB != null) rtB.Release();");
            ms.AppendLine("        if (displayTex != null) Destroy(displayTex);");
            ms.AppendLine("    }");
            ms.AppendLine("}");

            File.WriteAllText(managerFull, ms.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(managerAsset);

            return ToolResult<ProcGenReactionDiffusionResult>.Ok(new ProcGenReactionDiffusionResult
            {
                ComputeShaderPath = computeAsset,
                ManagerScriptPath = managerAsset,
                Width    = width,
                Height   = height,
                FeedRate = feed,
                KillRate = kill
            });
        }
    }
}
