using System.IO;
using System.Text;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;

namespace Mosaic.Bridge.Tools.ProcGen
{
    public static class ProcGenCaveTool
    {
        [MosaicTool("procgen/cave",
                    "Generates a cellular automata cave system compute shader and manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<ProcGenCaveResult> Execute(ProcGenCaveParams p)
        {
            int width      = p.Width ?? 64;
            int height     = p.Height ?? 64;
            int fillPct    = p.FillPercent ?? 45;
            int smooth     = p.SmoothIterations ?? 5;
            int seed       = p.Seed ?? 0;
            string outDir  = p.OutputDirectory ?? "Assets/Generated/ProcGen/Cave";

            if (!outDir.StartsWith("Assets/"))
                return ToolResult<ProcGenCaveResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            var fullDir = Path.Combine(Application.dataPath, "..", outDir);
            Directory.CreateDirectory(fullDir);

            // --- Compute Shader ---
            string computeName  = "CaveAutomata.compute";
            string computeAsset = outDir + "/" + computeName;
            string computeFull  = Path.Combine(fullDir, computeName);

            var cs = new StringBuilder();
            cs.AppendLine("// Generated by Mosaic Bridge - procgen/cave");
            cs.AppendLine("#pragma kernel InitCave");
            cs.AppendLine("#pragma kernel SmoothCave");
            cs.AppendLine();
            cs.AppendLine("RWTexture2D<float> caveMap;");
            cs.AppendLine("int _Width;");
            cs.AppendLine("int _Height;");
            cs.AppendLine("int _FillPercent;");
            cs.AppendLine("int _Seed;");
            cs.AppendLine();
            cs.AppendLine("uint hash(uint x)");
            cs.AppendLine("{");
            cs.AppendLine("    x ^= x >> 16;");
            cs.AppendLine("    x *= 0x45d9f3bu;");
            cs.AppendLine("    x ^= x >> 16;");
            cs.AppendLine("    x *= 0x45d9f3bu;");
            cs.AppendLine("    x ^= x >> 16;");
            cs.AppendLine("    return x;");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("[numthreads(8,8,1)]");
            cs.AppendLine("void InitCave(uint3 id : SV_DispatchThreadID)");
            cs.AppendLine("{");
            cs.AppendLine("    if ((int)id.x >= _Width || (int)id.y >= _Height) return;");
            cs.AppendLine("    // Border is always wall");
            cs.AppendLine("    if (id.x == 0 || id.y == 0 || (int)id.x == _Width - 1 || (int)id.y == _Height - 1)");
            cs.AppendLine("    {");
            cs.AppendLine("        caveMap[id.xy] = 1;");
            cs.AppendLine("        return;");
            cs.AppendLine("    }");
            cs.AppendLine("    uint h = hash(id.x + id.y * _Width + (uint)_Seed);");
            cs.AppendLine("    caveMap[id.xy] = (h % 100) < (uint)_FillPercent ? 1.0 : 0.0;");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("Texture2D<float> _ReadMap;");
            cs.AppendLine();
            cs.AppendLine("[numthreads(8,8,1)]");
            cs.AppendLine("void SmoothCave(uint3 id : SV_DispatchThreadID)");
            cs.AppendLine("{");
            cs.AppendLine("    if ((int)id.x >= _Width || (int)id.y >= _Height) return;");
            cs.AppendLine("    if (id.x == 0 || id.y == 0 || (int)id.x == _Width - 1 || (int)id.y == _Height - 1)");
            cs.AppendLine("    {");
            cs.AppendLine("        caveMap[id.xy] = 1;");
            cs.AppendLine("        return;");
            cs.AppendLine("    }");
            cs.AppendLine("    int neighbours = 0;");
            cs.AppendLine("    for (int dy = -1; dy <= 1; dy++)");
            cs.AppendLine("        for (int dx = -1; dx <= 1; dx++)");
            cs.AppendLine("            if (dx != 0 || dy != 0)");
            cs.AppendLine("                neighbours += _ReadMap[int2(id.x + dx, id.y + dy)] > 0.5 ? 1 : 0;");
            cs.AppendLine("    // B678/S345678");
            cs.AppendLine("    float current = _ReadMap[id.xy];");
            cs.AppendLine("    if (current > 0.5)");
            cs.AppendLine("        caveMap[id.xy] = neighbours >= 3 ? 1.0 : 0.0;");
            cs.AppendLine("    else");
            cs.AppendLine("        caveMap[id.xy] = neighbours >= 6 ? 1.0 : 0.0;");
            cs.AppendLine("}");

            File.WriteAllText(computeFull, cs.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(computeAsset);

            // --- Manager Script ---
            string managerName  = "CaveManager.cs";
            string managerAsset = outDir + "/" + managerName;
            string managerFull  = Path.Combine(fullDir, managerName);

            var ms = new StringBuilder();
            ms.AppendLine("// Generated by Mosaic Bridge - Customize as needed");
            ms.AppendLine("using UnityEngine;");
            ms.AppendLine("using UnityEngine.UI;");
            ms.AppendLine();
            ms.AppendLine("public class CaveManager : MonoBehaviour");
            ms.AppendLine("{");
            ms.AppendLine("    public ComputeShader computeShader;");
            ms.AppendLine($"    public int width = {width};");
            ms.AppendLine($"    public int height = {height};");
            ms.AppendLine($"    public int fillPercent = {fillPct};");
            ms.AppendLine($"    public int smoothIterations = {smooth};");
            ms.AppendLine($"    public int seed = {seed};");
            ms.AppendLine();
            ms.AppendLine("    RenderTexture caveRT;");
            ms.AppendLine("    RenderTexture readRT;");
            ms.AppendLine();
            ms.AppendLine("    void Start() { Generate(); }");
            ms.AppendLine();
            ms.AppendLine("    public void Generate()");
            ms.AppendLine("    {");
            ms.AppendLine("        caveRT = new RenderTexture(width, height, 0, RenderTextureFormat.RFloat);");
            ms.AppendLine("        caveRT.enableRandomWrite = true;");
            ms.AppendLine("        caveRT.Create();");
            ms.AppendLine();
            ms.AppendLine("        readRT = new RenderTexture(width, height, 0, RenderTextureFormat.RFloat);");
            ms.AppendLine("        readRT.enableRandomWrite = true;");
            ms.AppendLine("        readRT.Create();");
            ms.AppendLine();
            ms.AppendLine("        int initKernel = computeShader.FindKernel(\"InitCave\");");
            ms.AppendLine("        computeShader.SetInt(\"_Width\", width);");
            ms.AppendLine("        computeShader.SetInt(\"_Height\", height);");
            ms.AppendLine("        computeShader.SetInt(\"_FillPercent\", fillPercent);");
            ms.AppendLine("        computeShader.SetInt(\"_Seed\", seed);");
            ms.AppendLine("        computeShader.SetTexture(initKernel, \"caveMap\", caveRT);");
            ms.AppendLine("        computeShader.Dispatch(initKernel, Mathf.CeilToInt(width / 8f), Mathf.CeilToInt(height / 8f), 1);");
            ms.AppendLine();
            ms.AppendLine("        int smoothKernel = computeShader.FindKernel(\"SmoothCave\");");
            ms.AppendLine("        for (int i = 0; i < smoothIterations; i++)");
            ms.AppendLine("        {");
            ms.AppendLine("            Graphics.Blit(caveRT, readRT);");
            ms.AppendLine("            computeShader.SetTexture(smoothKernel, \"_ReadMap\", readRT);");
            ms.AppendLine("            computeShader.SetTexture(smoothKernel, \"caveMap\", caveRT);");
            ms.AppendLine("            computeShader.Dispatch(smoothKernel, Mathf.CeilToInt(width / 8f), Mathf.CeilToInt(height / 8f), 1);");
            ms.AppendLine("        }");
            ms.AppendLine();
            ms.AppendLine("        // Visualize on a RawImage or Renderer");
            ms.AppendLine("        var rawImage = GetComponent<RawImage>();");
            ms.AppendLine("        if (rawImage != null) rawImage.texture = caveRT;");
            ms.AppendLine("        var renderer = GetComponent<Renderer>();");
            ms.AppendLine("        if (renderer != null) renderer.material.mainTexture = caveRT;");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void OnDestroy()");
            ms.AppendLine("    {");
            ms.AppendLine("        if (caveRT != null) caveRT.Release();");
            ms.AppendLine("        if (readRT != null) readRT.Release();");
            ms.AppendLine("    }");
            ms.AppendLine("}");

            File.WriteAllText(managerFull, ms.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(managerAsset);

            return ToolResult<ProcGenCaveResult>.Ok(new ProcGenCaveResult
            {
                ComputeShaderPath = computeAsset,
                ManagerScriptPath = managerAsset,
                Width  = width,
                Height = height
            });
        }
    }
}
