using System.IO;
using System.Text;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Tools.Shared;

namespace Mosaic.Bridge.Tools.ProcGen
{
    public static class ProcGenHydraulicErodeTool
    {
        [MosaicTool("procgen/hydraulic-erode",
                    "Generates a hydraulic erosion simulation compute shader and manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<ProcGenHydraulicErodeResult> Execute(ProcGenHydraulicErodeParams p)
        {
            int   mapSize      = p.MapSize ?? 256;
            int   numDroplets  = p.NumDroplets ?? 70000;
            int   erosionRad   = p.ErosionRadius ?? 3;
            float inertia      = p.Inertia ?? 0.05f;
            float sedCapFactor = p.SedimentCapacityFactor ?? 4f;
            float minSedCap    = p.MinSedimentCapacity ?? 0.01f;
            float depositSpd   = p.DepositSpeed ?? 0.3f;
            float erodeSpd     = p.ErodeSpeed ?? 0.3f;
            float evapSpd      = p.EvaporateSpeed ?? 0.01f;
            float gravity      = p.Gravity ?? 4f;
            int   maxLife      = p.MaxDropletLifetime ?? 30;
            string outDir      = p.OutputDirectory ?? "Assets/Generated/ProcGen/HydraulicErode";

            if (!outDir.StartsWith("Assets/"))
                return ToolResult<ProcGenHydraulicErodeResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            AssetDatabaseHelper.EnsureFolder(outDir);
            var fullDir = Path.Combine(Application.dataPath, "..", outDir);

            // --- Compute Shader ---
            string computeName  = "HydraulicErosion.compute";
            string computeAsset = outDir + "/" + computeName;
            string computeFull  = Path.Combine(fullDir, computeName);

            var cs = new StringBuilder();
            cs.AppendLine("// Generated by Mosaic Bridge - procgen/hydraulic-erode");
            cs.AppendLine("#pragma kernel Erode");
            cs.AppendLine();
            cs.AppendLine("RWStructuredBuffer<float> heightMap;");
            cs.AppendLine("StructuredBuffer<int> randomIndices;");
            cs.AppendLine("int _MapSize;");
            cs.AppendLine("int _ErosionRadius;");
            cs.AppendLine("float _Inertia;");
            cs.AppendLine("float _SedimentCapacityFactor;");
            cs.AppendLine("float _MinSedimentCapacity;");
            cs.AppendLine("float _DepositSpeed;");
            cs.AppendLine("float _ErodeSpeed;");
            cs.AppendLine("float _EvaporateSpeed;");
            cs.AppendLine("float _Gravity;");
            cs.AppendLine("int _MaxDropletLifetime;");
            cs.AppendLine();
            cs.AppendLine("float2 calcGradient(float posX, float posY)");
            cs.AppendLine("{");
            cs.AppendLine("    int coordX = (int)posX;");
            cs.AppendLine("    int coordY = (int)posY;");
            cs.AppendLine("    float x = posX - coordX;");
            cs.AppendLine("    float y = posY - coordY;");
            cs.AppendLine("    int idx = coordY * _MapSize + coordX;");
            cs.AppendLine("    float hNW = heightMap[idx];");
            cs.AppendLine("    float hNE = heightMap[idx + 1];");
            cs.AppendLine("    float hSW = heightMap[idx + _MapSize];");
            cs.AppendLine("    float hSE = heightMap[idx + _MapSize + 1];");
            cs.AppendLine("    float gx = (hNE - hNW) * (1 - y) + (hSE - hSW) * y;");
            cs.AppendLine("    float gy = (hSW - hNW) * (1 - x) + (hSE - hNE) * x;");
            cs.AppendLine("    return float2(gx, gy);");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("float calcHeight(float posX, float posY)");
            cs.AppendLine("{");
            cs.AppendLine("    int coordX = (int)posX;");
            cs.AppendLine("    int coordY = (int)posY;");
            cs.AppendLine("    float x = posX - coordX;");
            cs.AppendLine("    float y = posY - coordY;");
            cs.AppendLine("    int idx = coordY * _MapSize + coordX;");
            cs.AppendLine("    return heightMap[idx] * (1-x)*(1-y) + heightMap[idx+1] * x*(1-y)");
            cs.AppendLine("         + heightMap[idx+_MapSize] * (1-x)*y + heightMap[idx+_MapSize+1] * x*y;");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("[numthreads(256,1,1)]");
            cs.AppendLine("void Erode(uint3 id : SV_DispatchThreadID)");
            cs.AppendLine("{");
            cs.AppendLine("    int dropIdx = randomIndices[id.x];");
            cs.AppendLine("    float posX = (float)(dropIdx % _MapSize);");
            cs.AppendLine("    float posY = (float)(dropIdx / _MapSize);");
            cs.AppendLine("    float dirX = 0;");
            cs.AppendLine("    float dirY = 0;");
            cs.AppendLine("    float speed = 1;");
            cs.AppendLine("    float water = 1;");
            cs.AppendLine("    float sediment = 0;");
            cs.AppendLine();
            cs.AppendLine("    for (int lifetime = 0; lifetime < _MaxDropletLifetime; lifetime++)");
            cs.AppendLine("    {");
            cs.AppendLine("        int nodeX = (int)posX;");
            cs.AppendLine("        int nodeY = (int)posY;");
            cs.AppendLine("        if (nodeX < 1 || nodeX >= _MapSize - 2 || nodeY < 1 || nodeY >= _MapSize - 2) break;");
            cs.AppendLine();
            cs.AppendLine("        float2 grad = calcGradient(posX, posY);");
            cs.AppendLine("        dirX = dirX * _Inertia - grad.x * (1 - _Inertia);");
            cs.AppendLine("        dirY = dirY * _Inertia - grad.y * (1 - _Inertia);");
            cs.AppendLine("        float len = max(0.0001, sqrt(dirX*dirX + dirY*dirY));");
            cs.AppendLine("        dirX /= len;");
            cs.AppendLine("        dirY /= len;");
            cs.AppendLine();
            cs.AppendLine("        float newPosX = posX + dirX;");
            cs.AppendLine("        float newPosY = posY + dirY;");
            cs.AppendLine("        if (newPosX < 1 || newPosX >= _MapSize - 2 || newPosY < 1 || newPosY >= _MapSize - 2) break;");
            cs.AppendLine();
            cs.AppendLine("        float oldHeight = calcHeight(posX, posY);");
            cs.AppendLine("        float newHeight = calcHeight(newPosX, newPosY);");
            cs.AppendLine("        float heightDiff = newHeight - oldHeight;");
            cs.AppendLine();
            cs.AppendLine("        float sedimentCapacity = max(-heightDiff * speed * water * _SedimentCapacityFactor, _MinSedimentCapacity);");
            cs.AppendLine();
            cs.AppendLine("        if (sediment > sedimentCapacity || heightDiff > 0)");
            cs.AppendLine("        {");
            cs.AppendLine("            float depositAmount = (heightDiff > 0) ? min(heightDiff, sediment) : (sediment - sedimentCapacity) * _DepositSpeed;");
            cs.AppendLine("            sediment -= depositAmount;");
            cs.AppendLine("            int idx = nodeY * _MapSize + nodeX;");
            cs.AppendLine("            heightMap[idx] += depositAmount;");
            cs.AppendLine("        }");
            cs.AppendLine("        else");
            cs.AppendLine("        {");
            cs.AppendLine("            float erodeAmount = min((sedimentCapacity - sediment) * _ErodeSpeed, -heightDiff);");
            cs.AppendLine("            for (int ey = -_ErosionRadius; ey <= _ErosionRadius; ey++)");
            cs.AppendLine("                for (int ex = -_ErosionRadius; ex <= _ErosionRadius; ex++)");
            cs.AppendLine("                {");
            cs.AppendLine("                    int erX = nodeX + ex;");
            cs.AppendLine("                    int erY = nodeY + ey;");
            cs.AppendLine("                    if (erX >= 0 && erX < _MapSize && erY >= 0 && erY < _MapSize)");
            cs.AppendLine("                    {");
            cs.AppendLine("                        float dist = sqrt((float)(ex*ex + ey*ey));");
            cs.AppendLine("                        if (dist <= _ErosionRadius)");
            cs.AppendLine("                        {");
            cs.AppendLine("                            float w = max(0, _ErosionRadius - dist) / _ErosionRadius;");
            cs.AppendLine("                            heightMap[erY * _MapSize + erX] -= erodeAmount * w * 0.1;");
            cs.AppendLine("                        }");
            cs.AppendLine("                    }");
            cs.AppendLine("                }");
            cs.AppendLine("            sediment += erodeAmount;");
            cs.AppendLine("        }");
            cs.AppendLine();
            cs.AppendLine("        speed = sqrt(max(0, speed*speed + heightDiff * _Gravity));");
            cs.AppendLine("        water *= (1 - _EvaporateSpeed);");
            cs.AppendLine("        posX = newPosX;");
            cs.AppendLine("        posY = newPosY;");
            cs.AppendLine("    }");
            cs.AppendLine("}");

            File.WriteAllText(computeFull, cs.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(computeAsset);

            // --- Manager Script ---
            string managerName  = "HydraulicErodeManager.cs";
            string managerAsset = outDir + "/" + managerName;
            string managerFull  = Path.Combine(fullDir, managerName);

            var ms = new StringBuilder();
            ms.AppendLine("// Generated by Mosaic Bridge - Customize as needed");
            ms.AppendLine("using UnityEngine;");
            ms.AppendLine();
            ms.AppendLine("[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]");
            ms.AppendLine("public class HydraulicErodeManager : MonoBehaviour");
            ms.AppendLine("{");
            ms.AppendLine("    public ComputeShader computeShader;");
            ms.AppendLine($"    public int mapSize = {mapSize};");
            ms.AppendLine($"    public int numDroplets = {numDroplets};");
            ms.AppendLine($"    public int erosionRadius = {erosionRad};");
            ms.AppendLine($"    public float inertia = {inertia}f;");
            ms.AppendLine($"    public float sedimentCapacityFactor = {sedCapFactor}f;");
            ms.AppendLine($"    public float minSedimentCapacity = {minSedCap}f;");
            ms.AppendLine($"    public float depositSpeed = {depositSpd}f;");
            ms.AppendLine($"    public float erodeSpeed = {erodeSpd}f;");
            ms.AppendLine($"    public float evaporateSpeed = {evapSpd}f;");
            ms.AppendLine($"    public float gravity = {gravity}f;");
            ms.AppendLine($"    public int maxDropletLifetime = {maxLife};");
            ms.AppendLine("    public float terrainScale = 50f;");
            ms.AppendLine("    public float terrainHeight = 20f;");
            ms.AppendLine();
            ms.AppendLine("    void Start() { Generate(); }");
            ms.AppendLine();
            ms.AppendLine("    public void Generate()");
            ms.AppendLine("    {");
            ms.AppendLine("        int totalCells = mapSize * mapSize;");
            ms.AppendLine("        float[] heights = new float[totalCells];");
            ms.AppendLine("        // Generate initial Perlin noise heightmap");
            ms.AppendLine("        for (int y = 0; y < mapSize; y++)");
            ms.AppendLine("            for (int x = 0; x < mapSize; x++)");
            ms.AppendLine("            {");
            ms.AppendLine("                float nx = (float)x / mapSize * terrainScale;");
            ms.AppendLine("                float ny = (float)y / mapSize * terrainScale;");
            ms.AppendLine("                heights[y * mapSize + x] = Mathf.PerlinNoise(nx, ny) * terrainHeight;");
            ms.AppendLine("            }");
            ms.AppendLine();
            ms.AppendLine("        ComputeBuffer heightBuf = new ComputeBuffer(totalCells, sizeof(float));");
            ms.AppendLine("        heightBuf.SetData(heights);");
            ms.AppendLine();
            ms.AppendLine("        // Random starting positions");
            ms.AppendLine("        int[] randIdx = new int[numDroplets];");
            ms.AppendLine("        for (int i = 0; i < numDroplets; i++)");
            ms.AppendLine("            randIdx[i] = Random.Range(mapSize + 1, totalCells - mapSize - 1);");
            ms.AppendLine("        ComputeBuffer randBuf = new ComputeBuffer(numDroplets, sizeof(int));");
            ms.AppendLine("        randBuf.SetData(randIdx);");
            ms.AppendLine();
            ms.AppendLine("        int kernel = computeShader.FindKernel(\"Erode\");");
            ms.AppendLine("        computeShader.SetBuffer(kernel, \"heightMap\", heightBuf);");
            ms.AppendLine("        computeShader.SetBuffer(kernel, \"randomIndices\", randBuf);");
            ms.AppendLine("        computeShader.SetInt(\"_MapSize\", mapSize);");
            ms.AppendLine("        computeShader.SetInt(\"_ErosionRadius\", erosionRadius);");
            ms.AppendLine("        computeShader.SetFloat(\"_Inertia\", inertia);");
            ms.AppendLine("        computeShader.SetFloat(\"_SedimentCapacityFactor\", sedimentCapacityFactor);");
            ms.AppendLine("        computeShader.SetFloat(\"_MinSedimentCapacity\", minSedimentCapacity);");
            ms.AppendLine("        computeShader.SetFloat(\"_DepositSpeed\", depositSpeed);");
            ms.AppendLine("        computeShader.SetFloat(\"_ErodeSpeed\", erodeSpeed);");
            ms.AppendLine("        computeShader.SetFloat(\"_EvaporateSpeed\", evaporateSpeed);");
            ms.AppendLine("        computeShader.SetFloat(\"_Gravity\", gravity);");
            ms.AppendLine("        computeShader.SetInt(\"_MaxDropletLifetime\", maxDropletLifetime);");
            ms.AppendLine("        computeShader.Dispatch(kernel, Mathf.CeilToInt(numDroplets / 256f), 1, 1);");
            ms.AppendLine();
            ms.AppendLine("        heightBuf.GetData(heights);");
            ms.AppendLine("        heightBuf.Release();");
            ms.AppendLine("        randBuf.Release();");
            ms.AppendLine();
            ms.AppendLine("        BuildMesh(heights);");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void BuildMesh(float[] heights)");
            ms.AppendLine("    {");
            ms.AppendLine("        Vector3[] verts = new Vector3[mapSize * mapSize];");
            ms.AppendLine("        Vector2[] uvs   = new Vector2[mapSize * mapSize];");
            ms.AppendLine("        for (int z = 0; z < mapSize; z++)");
            ms.AppendLine("            for (int x = 0; x < mapSize; x++)");
            ms.AppendLine("            {");
            ms.AppendLine("                int i = z * mapSize + x;");
            ms.AppendLine("                verts[i] = new Vector3(x, heights[i], z);");
            ms.AppendLine("                uvs[i]   = new Vector2((float)x / mapSize, (float)z / mapSize);");
            ms.AppendLine("            }");
            ms.AppendLine("        int[] tris = new int[(mapSize - 1) * (mapSize - 1) * 6];");
            ms.AppendLine("        int t = 0;");
            ms.AppendLine("        for (int z = 0; z < mapSize - 1; z++)");
            ms.AppendLine("            for (int x = 0; x < mapSize - 1; x++)");
            ms.AppendLine("            {");
            ms.AppendLine("                int i = z * mapSize + x;");
            ms.AppendLine("                tris[t++] = i; tris[t++] = i + mapSize; tris[t++] = i + 1;");
            ms.AppendLine("                tris[t++] = i + 1; tris[t++] = i + mapSize; tris[t++] = i + mapSize + 1;");
            ms.AppendLine("            }");
            ms.AppendLine("        Mesh mesh = new Mesh();");
            ms.AppendLine("        mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;");
            ms.AppendLine("        mesh.vertices = verts;");
            ms.AppendLine("        mesh.uv = uvs;");
            ms.AppendLine("        mesh.triangles = tris;");
            ms.AppendLine("        mesh.RecalculateNormals();");
            ms.AppendLine("        GetComponent<MeshFilter>().mesh = mesh;");
            ms.AppendLine("    }");
            ms.AppendLine("}");

            File.WriteAllText(managerFull, ms.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(managerAsset);

            return ToolResult<ProcGenHydraulicErodeResult>.Ok(new ProcGenHydraulicErodeResult
            {
                ComputeShaderPath = computeAsset,
                ManagerScriptPath = managerAsset,
                MapSize     = mapSize,
                NumDroplets = numDroplets
            });
        }
    }
}
