using System.IO;
using System.Text;
using UnityEngine;
using UnityEditor;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;

namespace Mosaic.Bridge.Tools.ProcGen
{
    public static class ProcGenTerrainTool
    {
        [MosaicTool("procgen/terrain",
                    "Generates a Perlin noise terrain compute shader and MonoBehaviour manager script",
                    isReadOnly: false, Context = ToolContext.Both)]
        public static ToolResult<ProcGenTerrainResult> Execute(ProcGenTerrainParams p)
        {
            int   width      = p.Width ?? 256;
            int   depth      = p.Depth ?? 256;
            int   octaves    = p.Octaves ?? 6;
            float persistence = p.Persistence ?? 0.5f;
            float lacunarity = p.Lacunarity ?? 2.0f;
            int   seed       = p.Seed ?? 0;
            float scale      = p.Scale ?? 50f;
            float heightMul  = p.HeightMultiplier ?? 20f;
            string outDir    = p.OutputDirectory ?? "Assets/Generated/ProcGen/Terrain";

            if (!outDir.StartsWith("Assets/"))
                return ToolResult<ProcGenTerrainResult>.Fail(
                    "OutputDirectory must start with 'Assets/'", ErrorCodes.INVALID_PARAM);

            var fullDir = Path.Combine(Application.dataPath, "..", outDir);
            Directory.CreateDirectory(fullDir);

            // --- Compute Shader ---
            string computeName = "TerrainNoise.compute";
            string computeAsset = outDir + "/" + computeName;
            string computeFull  = Path.Combine(fullDir, computeName);

            var cs = new StringBuilder();
            cs.AppendLine("// Generated by Mosaic Bridge - procgen/terrain");
            cs.AppendLine("#pragma kernel GenerateTerrain");
            cs.AppendLine();
            cs.AppendLine("RWStructuredBuffer<float> heightMap;");
            cs.AppendLine();
            cs.AppendLine("int _Width;");
            cs.AppendLine("int _Depth;");
            cs.AppendLine("int _Octaves;");
            cs.AppendLine("float _Persistence;");
            cs.AppendLine("float _Lacunarity;");
            cs.AppendLine("int _Seed;");
            cs.AppendLine("float _Scale;");
            cs.AppendLine("float _HeightMultiplier;");
            cs.AppendLine();
            cs.AppendLine("// Hash-based noise helpers");
            cs.AppendLine("float hash(float2 p)");
            cs.AppendLine("{");
            cs.AppendLine("    float3 p3 = frac(float3(p.xyx) * 0.1031);");
            cs.AppendLine("    p3 += dot(p3, p3.yzx + 33.33);");
            cs.AppendLine("    return frac((p3.x + p3.y) * p3.z);");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("float noise(float2 p)");
            cs.AppendLine("{");
            cs.AppendLine("    float2 i = floor(p);");
            cs.AppendLine("    float2 f = frac(p);");
            cs.AppendLine("    float2 u = f * f * (3.0 - 2.0 * f);");
            cs.AppendLine("    float a = hash(i + float2(0, 0));");
            cs.AppendLine("    float b = hash(i + float2(1, 0));");
            cs.AppendLine("    float c = hash(i + float2(0, 1));");
            cs.AppendLine("    float d = hash(i + float2(1, 1));");
            cs.AppendLine("    return lerp(lerp(a, b, u.x), lerp(c, d, u.x), u.y);");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("float fbm(float2 p, int octaves, float persistence, float lacunarity)");
            cs.AppendLine("{");
            cs.AppendLine("    float total = 0;");
            cs.AppendLine("    float amplitude = 1;");
            cs.AppendLine("    float frequency = 1;");
            cs.AppendLine("    float maxVal = 0;");
            cs.AppendLine("    for (int i = 0; i < octaves; i++)");
            cs.AppendLine("    {");
            cs.AppendLine("        total += noise(p * frequency) * amplitude;");
            cs.AppendLine("        maxVal += amplitude;");
            cs.AppendLine("        amplitude *= persistence;");
            cs.AppendLine("        frequency *= lacunarity;");
            cs.AppendLine("    }");
            cs.AppendLine("    return total / maxVal;");
            cs.AppendLine("}");
            cs.AppendLine();
            cs.AppendLine("[numthreads(8,8,1)]");
            cs.AppendLine("void GenerateTerrain(uint3 id : SV_DispatchThreadID)");
            cs.AppendLine("{");
            cs.AppendLine("    if ((int)id.x >= _Width || (int)id.y >= _Depth) return;");
            cs.AppendLine("    float2 uv = float2(id.x, id.y) / _Scale + float2(_Seed, _Seed);");
            cs.AppendLine("    float h = fbm(uv, _Octaves, _Persistence, _Lacunarity) * _HeightMultiplier;");
            cs.AppendLine("    heightMap[id.y * _Width + id.x] = h;");
            cs.AppendLine("}");

            File.WriteAllText(computeFull, cs.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(computeAsset);

            // --- Manager Script ---
            string managerName  = "TerrainManager.cs";
            string managerAsset = outDir + "/" + managerName;
            string managerFull  = Path.Combine(fullDir, managerName);

            var ms = new StringBuilder();
            ms.AppendLine("// Generated by Mosaic Bridge - Customize as needed");
            ms.AppendLine("using UnityEngine;");
            ms.AppendLine();
            ms.AppendLine("[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]");
            ms.AppendLine("public class TerrainManager : MonoBehaviour");
            ms.AppendLine("{");
            ms.AppendLine("    public ComputeShader computeShader;");
            ms.AppendLine($"    public int width = {width};");
            ms.AppendLine($"    public int depth = {depth};");
            ms.AppendLine($"    public int octaves = {octaves};");
            ms.AppendLine($"    public float persistence = {persistence}f;");
            ms.AppendLine($"    public float lacunarity = {lacunarity}f;");
            ms.AppendLine($"    public int seed = {seed};");
            ms.AppendLine($"    public float scale = {scale}f;");
            ms.AppendLine($"    public float heightMultiplier = {heightMul}f;");
            ms.AppendLine();
            ms.AppendLine("    void Start() { Generate(); }");
            ms.AppendLine();
            ms.AppendLine("    public void Generate()");
            ms.AppendLine("    {");
            ms.AppendLine("        int count = width * depth;");
            ms.AppendLine("        ComputeBuffer buffer = new ComputeBuffer(count, sizeof(float));");
            ms.AppendLine("        int kernel = computeShader.FindKernel(\"GenerateTerrain\");");
            ms.AppendLine("        computeShader.SetBuffer(kernel, \"heightMap\", buffer);");
            ms.AppendLine("        computeShader.SetInt(\"_Width\", width);");
            ms.AppendLine("        computeShader.SetInt(\"_Depth\", depth);");
            ms.AppendLine("        computeShader.SetInt(\"_Octaves\", octaves);");
            ms.AppendLine("        computeShader.SetFloat(\"_Persistence\", persistence);");
            ms.AppendLine("        computeShader.SetFloat(\"_Lacunarity\", lacunarity);");
            ms.AppendLine("        computeShader.SetInt(\"_Seed\", seed);");
            ms.AppendLine("        computeShader.SetFloat(\"_Scale\", scale);");
            ms.AppendLine("        computeShader.SetFloat(\"_HeightMultiplier\", heightMultiplier);");
            ms.AppendLine("        computeShader.Dispatch(kernel, Mathf.CeilToInt(width / 8f), Mathf.CeilToInt(depth / 8f), 1);");
            ms.AppendLine();
            ms.AppendLine("        float[] heights = new float[count];");
            ms.AppendLine("        buffer.GetData(heights);");
            ms.AppendLine("        buffer.Release();");
            ms.AppendLine();
            ms.AppendLine("        BuildMesh(heights);");
            ms.AppendLine("    }");
            ms.AppendLine();
            ms.AppendLine("    void BuildMesh(float[] heights)");
            ms.AppendLine("    {");
            ms.AppendLine("        Vector3[] verts = new Vector3[width * depth];");
            ms.AppendLine("        Vector2[] uvs   = new Vector2[width * depth];");
            ms.AppendLine("        for (int z = 0; z < depth; z++)");
            ms.AppendLine("            for (int x = 0; x < width; x++)");
            ms.AppendLine("            {");
            ms.AppendLine("                int i = z * width + x;");
            ms.AppendLine("                verts[i] = new Vector3(x, heights[i], z);");
            ms.AppendLine("                uvs[i]   = new Vector2((float)x / width, (float)z / depth);");
            ms.AppendLine("            }");
            ms.AppendLine();
            ms.AppendLine("        int[] tris = new int[(width - 1) * (depth - 1) * 6];");
            ms.AppendLine("        int t = 0;");
            ms.AppendLine("        for (int z = 0; z < depth - 1; z++)");
            ms.AppendLine("            for (int x = 0; x < width - 1; x++)");
            ms.AppendLine("            {");
            ms.AppendLine("                int i = z * width + x;");
            ms.AppendLine("                tris[t++] = i; tris[t++] = i + width; tris[t++] = i + 1;");
            ms.AppendLine("                tris[t++] = i + 1; tris[t++] = i + width; tris[t++] = i + width + 1;");
            ms.AppendLine("            }");
            ms.AppendLine();
            ms.AppendLine("        Mesh mesh = new Mesh();");
            ms.AppendLine("        mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;");
            ms.AppendLine("        mesh.vertices = verts;");
            ms.AppendLine("        mesh.uv = uvs;");
            ms.AppendLine("        mesh.triangles = tris;");
            ms.AppendLine("        mesh.RecalculateNormals();");
            ms.AppendLine("        GetComponent<MeshFilter>().mesh = mesh;");
            ms.AppendLine("    }");
            ms.AppendLine("}");

            File.WriteAllText(managerFull, ms.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(managerAsset);

            return ToolResult<ProcGenTerrainResult>.Ok(new ProcGenTerrainResult
            {
                ComputeShaderPath = computeAsset,
                ManagerScriptPath = managerAsset,
                Width   = width,
                Depth   = depth,
                Octaves = octaves
            });
        }
    }
}
