using Mosaic.Bridge.Contracts.Attributes;

namespace Mosaic.Bridge.Tools.Models
{
    public sealed class ModelClipInput
    {
        /// <summary>Name of the split clip to create (e.g. "Idle", "Walk").</summary>
        [Required] public string Name { get; set; }
        /// <summary>First frame of the source take this clip spans.</summary>
        public float FirstFrame { get; set; }
        /// <summary>Last frame of the source take this clip spans.</summary>
        public float LastFrame { get; set; }
        /// <summary>Name of the source take to split (defaults to the model's first take when omitted).</summary>
        public string TakeName { get; set; }
        public bool LoopTime { get; set; }
        public bool LoopPose { get; set; }
        public bool KeepOriginalOrientation { get; set; }
        public bool KeepOriginalPositionY { get; set; }
        public bool KeepOriginalPositionXZ { get; set; }
        public bool HeightFromFeet { get; set; }
        public bool Mirror { get; set; }
    }

    public sealed class ModelSetImportSettingsParams
    {
        /// <summary>Asset path to the model (e.g. "Assets/Characters/Hero.fbx").</summary>
        [Required] public string AssetPath { get; set; }

        /// <summary>Animator generation mode: None, Legacy, Generic, Human. Null to leave unchanged.</summary>
        public string AnimationType { get; set; }

        /// <summary>Avatar generation: NoAvatar, CreateFromThisModel, CopyFromOther. Null to leave unchanged.</summary>
        public string AvatarSetup { get; set; }

        /// <summary>Asset path of an existing Avatar to copy the HumanDescription from
        /// (required when AvatarSetup="CopyFromOther").</summary>
        public string SourceAvatarPath { get; set; }

        /// <summary>Whether to import animation from the file. Null to leave unchanged.</summary>
        public bool? ImportAnimation { get; set; }

        /// <summary>Global scale factor applied on import — the fix for "my model is 100x too
        /// big/small" (a common Mixamo/DCC-tool unit mismatch). Null to leave unchanged.</summary>
        public float? GlobalScale { get; set; }

        /// <summary>Use the file's own embedded scale factor instead of GlobalScale. Null to leave unchanged.</summary>
        public bool? UseFileScale { get; set; }

        /// <summary>Material import mode: None, ImportStandard, ImportViaMaterialDescription.
        /// "None" is the fix for "why is my model pink" (missing/unresolved materials). Null to leave unchanged.</summary>
        public string MaterialImportMode { get; set; }

        /// <summary>Whether mesh vertices/indices are readable from script at runtime. Null to leave unchanged.</summary>
        public bool? IsReadable { get; set; }

        /// <summary>Mesh compression: Off, Low, Medium, High. Null to leave unchanged.</summary>
        public string MeshCompression { get; set; }

        /// <summary>Add mesh colliders to imported meshes. Null to leave unchanged.</summary>
        public bool? AddCollider { get; set; }

        /// <summary>Generate a secondary UV set for lightmapping. Null to leave unchanged.</summary>
        public bool? GenerateSecondaryUV { get; set; }

        /// <summary>Split the model's take(s) into named animation clips (Mixamo/asset-store FBX
        /// convention — one long take becomes "Idle"/"Walk"/"Run" ranges). Replaces any existing
        /// clipAnimations. Omit to leave existing clips unchanged.</summary>
        public ModelClipInput[] Clips { get; set; }

        /// <summary>Extract the model's embedded textures to disk alongside the asset (or into
        /// ExtractTexturesPath when given). Runs after all other settings are applied.</summary>
        public bool ExtractTextures { get; set; }

        /// <summary>Destination folder for ExtractTextures. Defaults to the model's own folder.</summary>
        public string ExtractTexturesPath { get; set; }

        /// <summary>After applying settings, search the project for matching materials by name
        /// and use them instead of materials embedded/generated by the importer.</summary>
        public bool SearchAndRemapMaterials { get; set; }
    }
}
