using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Newtonsoft.Json.Linq;
using Mosaic.Bridge.Contracts.Attributes;
using Mosaic.Bridge.Contracts.Envelopes;
using Mosaic.Bridge.Contracts.Errors;
using Mosaic.Bridge.Core.Knowledge;

namespace Mosaic.Bridge.Tools.AI
{
    /// <summary>
    /// <c>ai/generate-asset</c> — prepares a Unity AI generation request.
    ///
    /// The bridge deliberately does not call Unity AI itself. Generation is a paid cloud
    /// service billed in Unity credits, and Unity's terms (updated 2026-06-30) restrict
    /// automated callers invoking their offerings to "Authorized Agentic Access", with a
    /// carve-out for integrations that work only with the local Editor and project files.
    /// Everything else the bridge does sits inside that carve-out; driving generation
    /// directly would not. Unity ships its own authorized asset-generation MCP, so this
    /// tool builds the request and lets that authorized channel execute it.
    ///
    /// What the bridge adds is the part Unity's generator has no access to: measured
    /// values from the bundled PBR knowledge base, folded into the prompt with their
    /// source recorded, so "oak floor" becomes a prompt carrying real albedo and
    /// roughness rather than the model's guess.
    /// </summary>
    public static class AiGenerateAssetTool
    {
        // Asset kind -> Unity AI command + advisory models. The live catalog is
        // entitlement-scoped and changes, so these are hints to be confirmed, not truth.
        private static readonly Dictionary<string, (string Command, string[] Models, string Ext)> Kinds =
            new Dictionary<string, (string, string[], string)>(StringComparer.OrdinalIgnoreCase)
            {
                ["Material"]  = ("GenerateMaterial", new[] { "gemini-3.1-flash-texture", "realistic-textures-3-0", "unity-texture2d" }, "mat"),
                ["Texture"]   = ("GenerateImage",    new[] { "gemini-3.1-flash-texture", "unity-texture2d" },                          "png"),
                ["Sprite"]    = ("GenerateSprite",   new[] { "flux-2-dev", "gpt-image-1", "game-ui-essentials-2" },                    "png"),
                ["Image"]     = ("GenerateImage",    new[] { "gpt-image-1-5", "gemini-3.1-flash", "flux-2-pro" },                      "png"),
                ["Sound"]     = ("GenerateSound",    new[] { "elevenlabs-sound-effects-v2" },                                          "wav"),
                ["Animation"] = ("GenerateAnimation", new string[0],                                                                   "anim"),
                ["Model3D"]   = ("GenerateMesh",     new string[0],                                                                    "fbx"),
            };

        [MosaicTool("ai/generate-asset",
                    "Prepares a Unity AI asset generation request (texture, material, sprite, image, sound, animation, 3D model). " +
                    "Enriches the prompt with measured PBR values from the knowledge base and returns the command, model hints and save path. " +
                    "Does NOT generate: execute the returned request via Unity's official asset-generation MCP when Mode is 'unity-mcp'. " +
                    "Generating spends the user's Unity AI credits — always confirm with them first. " +
                    "When Mode is 'handoff', Unity AI is unavailable and the prompt should be generated by hand.",
                    isReadOnly: true, Context = ToolContext.Editor)]
        public static ToolResult<AiGenerateAssetResult> Execute(AiGenerateAssetParams p)
        {
            if (p == null)
                return ToolResult<AiGenerateAssetResult>.Fail("Params are required", ErrorCodes.INVALID_PARAM);
            if (string.IsNullOrWhiteSpace(p.Prompt))
                return ToolResult<AiGenerateAssetResult>.Fail(
                    "Prompt is required — describe the asset (e.g. 'seamless dark oak floor planks, PBR').",
                    ErrorCodes.INVALID_PARAM);
            if (string.IsNullOrWhiteSpace(p.Name))
                return ToolResult<AiGenerateAssetResult>.Fail(
                    "Name is required — a short asset name (e.g. 'floor-oak').", ErrorCodes.INVALID_PARAM);
            if (string.IsNullOrWhiteSpace(p.AssetType) || !Kinds.TryGetValue(p.AssetType, out var kind))
                return ToolResult<AiGenerateAssetResult>.Fail(
                    $"Unknown AssetType '{p.AssetType}'. Use one of: {string.Join(", ", Kinds.Keys)}.",
                    ErrorCodes.INVALID_PARAM);

            var folder = string.IsNullOrWhiteSpace(p.DestinationFolder)
                ? "Assets/Generated"
                : p.DestinationFolder.Replace('\\', '/').TrimEnd('/');
            if (!folder.StartsWith("Assets/", StringComparison.Ordinal) && folder != "Assets")
                return ToolResult<AiGenerateAssetResult>.Fail(
                    $"DestinationFolder must be under Assets/ (got '{folder}').", ErrorCodes.INVALID_PARAM);

            var prompt = p.Prompt.Trim();
            var applied = new List<string>();
            if (p.GroundInKnowledgeBase ?? true)
                prompt = GroundPrompt(prompt, applied);

            var available = UnityAiProbe.IsAvailable(out var detail);
            var safeName = SanitizeName(p.Name);

            return ToolResult<AiGenerateAssetResult>.Ok(new AiGenerateAssetResult
            {
                Mode             = available ? "unity-mcp" : "handoff",
                UnityAiAvailable = available,
                DetectedVia      = detail,
                Command          = kind.Command,
                SuggestedModels  = kind.Models,
                Prompt           = prompt,
                SavePath         = $"{folder}/{safeName}.{kind.Ext}",
                Width            = p.Width,
                Height           = p.Height,
                DurationSeconds  = p.DurationSeconds,
                KnowledgeApplied = applied.ToArray(),
                ConsumesCredits  = available,
                NextStep         = available
                    ? "Confirm with the user that they want to spend Unity AI credits, then call Unity's " +
                      "official asset-generation MCP with this Command, Prompt and SavePath. Verify the model " +
                      "id against Unity's model-listing tool first — the catalog is entitlement-scoped and changes."
                    : "Unity AI was not detected in this Editor. Install it via Package Manager > Install AI while " +
                      "signed in to an account with AI access, or generate this prompt by hand and import the file " +
                      "into the SavePath shown.",
            });
        }

        /// <summary>
        /// Folds measured values into the prompt when the description names a material the
        /// knowledge base knows. Every injected number is recorded in <paramref name="applied"/>
        /// with its source, so the result stays auditable.
        /// </summary>
        private static string GroundPrompt(string prompt, List<string> applied)
        {
            JArray materials;
            try { materials = KnowledgeBase.GetAllPbrMaterials(); }
            catch { return prompt; }
            if (materials == null) return prompt;

            var match = FindMaterial(prompt, materials);
            if (match == null) return prompt;

            var name = match["name"]?.Value<string>();
            var albedo = match["albedo"] as JArray;
            var roughness = match["roughness"]?.Value<double?>();
            var metalness = match["metalness"]?.Value<double?>();
            var source = match["source"]?.Value<string>() ?? "knowledge base";

            var parts = new List<string>();
            if (albedo != null && albedo.Count >= 3)
            {
                var rgb = string.Join(", ", albedo.Take(3).Select(v => v.Value<double>().ToString("0.###", CultureInfo.InvariantCulture)));
                parts.Add($"linear albedo ({rgb})");
                applied.Add($"{name}: albedo [{rgb}] — {source}");
            }
            if (roughness.HasValue)
            {
                parts.Add($"roughness {roughness.Value.ToString("0.##", CultureInfo.InvariantCulture)}");
                applied.Add($"{name}: roughness {roughness.Value.ToString("0.##", CultureInfo.InvariantCulture)} — {source}");
            }
            if (metalness.HasValue)
            {
                parts.Add($"metalness {metalness.Value.ToString("0.##", CultureInfo.InvariantCulture)}");
                applied.Add($"{name}: metalness {metalness.Value.ToString("0.##", CultureInfo.InvariantCulture)} — {source}");
            }

            return parts.Count == 0 ? prompt : $"{prompt}. Physically accurate: {string.Join(", ", parts)}";
        }

        /// <summary>
        /// Matches a knowledge-base material against the prompt. Entry names are like
        /// "wood_oak", so each underscore-separated token must appear in the prompt —
        /// "oak floor" matches wood_oak, while "oak" alone does not match wood_pine.
        /// The most specific (most tokens) match wins.
        /// </summary>
        private static JToken FindMaterial(string prompt, JArray materials)
        {
            var haystack = prompt.ToLowerInvariant();
            JToken best = null;
            var bestScore = 0;

            foreach (var m in materials)
            {
                var name = m["name"]?.Value<string>();
                if (string.IsNullOrEmpty(name)) continue;

                var tokens = name.Split(new[] { '_', '-' }, StringSplitOptions.RemoveEmptyEntries);
                if (tokens.Length == 0) continue;
                if (!tokens.All(t => haystack.Contains(t.ToLowerInvariant()))) continue;

                if (tokens.Length > bestScore)
                {
                    bestScore = tokens.Length;
                    best = m;
                }
            }

            return best;
        }

        private static string SanitizeName(string name)
        {
            var cleaned = new string(name.Trim()
                .Select(c => char.IsLetterOrDigit(c) || c == '-' || c == '_' ? c : '-')
                .ToArray());
            while (cleaned.Contains("--")) cleaned = cleaned.Replace("--", "-");
            return cleaned.Trim('-');
        }
    }
}
